USE [master]
GO

IF EXISTS (SELECT 1 FROM sys.databases WHERE [name] = N'GalaxySMS')
begin
	DROP DATABASE GalaxySMS
END

/****** Object:  Database [GalaxySMS]    Script Date: 4/21/2022 4:08:27 PM ******/
CREATE DATABASE [GalaxySMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GalaxySMS', FILENAME = N'D:\SQLDataFiles\MSSQL15.SQL2019DEV\MSSQL\DATA\GalaxySMSuk1.mdf' , SIZE = 96064KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
 FILEGROUP [GalaxySMSFileStreamFileGroup1] CONTAINS FILESTREAM  DEFAULT
( NAME = N'GalaxySMSFileStream', FILENAME = N'D:\SQLDataFiles\MSSQL15.SQL2019DEV\MSSQL\DATA\GalaxySMSFileStreamUk1' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'GalaxySMS_log', FILENAME = N'D:\SQLDataFiles\MSSQL15.SQL2019DEV\MSSQL\DATA\GalaxySMSuk1_log.ldf' , SIZE = 65536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GalaxySMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GalaxySMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GalaxySMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GalaxySMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GalaxySMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GalaxySMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [GalaxySMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GalaxySMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GalaxySMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GalaxySMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GalaxySMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GalaxySMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GalaxySMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GalaxySMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GalaxySMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GalaxySMS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GalaxySMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GalaxySMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GalaxySMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GalaxySMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GalaxySMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GalaxySMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GalaxySMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GalaxySMS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GalaxySMS] SET  MULTI_USER 
GO

ALTER DATABASE [GalaxySMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GalaxySMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GalaxySMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GalaxySMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GalaxySMS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GalaxySMS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GalaxySMS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GalaxySMS] SET  READ_WRITE 
GO

