//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using GCS.Core.Common.Contracts;
	using GCS.Core.Common.Core;
    public partial class gcsLargeObjectStorage : EntityBase, IIdentifiableEntity, IEquatable<gcsLargeObjectStorage>, ITableEntityBase
    {
    /*	// Move to partial class
    using System;
    using System.Collections.Generic;
    using GCS.Core.Common.Contracts;
	using GCS.Core.Common.Core;
    using GCS.Core.Common.Extensions;
    
    namespace GalaxySMS.Business.Entities
    {
        public partial class gcsLargeObjectStorage
        {
        	public gcsLargeObjectStorage()
        	{
        		Initialize();
        	}
        
        	public gcsLargeObjectStorage(gcsLargeObjectStorage e)
        	{
        		Initialize(e);
        	}
        
        	public void Initialize()
        	{
        	}
        
        	public void Initialize(gcsLargeObjectStorage e)
        	{
        		Initialize();
        		if( e == null )
        			return;
        
        		this.IsDirty = e.IsDirty;
        		this.Uid = e.Uid;
        		this.EntityId = e.EntityId;
        		this.UniqueTag = e.UniqueTag;
        		this.DataType = e.DataType;
        		this.TextData = e.TextData;
        		this.FileStreamData = e.FileStreamData;
        		this.BlobData = e.BlobData;
        		this.InsertName = e.InsertName;
        		this.InsertDate = e.InsertDate;
        		this.UpdateName = e.UpdateName;
        		this.UpdateDate = e.UpdateDate;
        		this.ConcurrencyValue = e.ConcurrencyValue;
        		
        	}
        
        	public bool IsAnythingDirty
        	{
        		get
        		{
        			//foreach( var o in InterfaceBoardSections)
        			//{
        			//	if (o.IsAnythingDirty == true)
        			//		return true;
        			//}
        			return IsDirty;                
        		}
        	}
        
        	public gcsLargeObjectStorage Clone(gcsLargeObjectStorage e)
        	{
        		return new gcsLargeObjectStorage(e);
        	}
        
        	public bool Equals(gcsLargeObjectStorage other)
        	{
        		return base.Equals(other);
        	}
        	
        	public bool IsPrimaryKeyEqual(gcsLargeObjectStorage other)
        	{
        		if( other == null ) 
        			return false;
        
        		if(other.Uid != this.Uid )
        			return false;
        		return true;
        	}
        
        	public override int GetHashCode()
        	{
        		return base.GetHashCode();
        	}
        
        	public override string ToString()
        	{
        		return base.ToString();
        	}
        }
    }
    */
    	public System.Guid Uid { get; set; }
    	public Nullable<System.Guid> EntityId { get; set; }
    	public string UniqueTag { get; set; }
    	public string DataType { get; set; }
    	public string TextData { get; set; }
    	public byte[] FileStreamData { get; set; }
    	public byte[] BlobData { get; set; }
    	public string InsertName { get; set; }
    	public System.DateTimeOffset InsertDate { get; set; }
    	public string UpdateName { get; set; }
    	public Nullable<System.DateTimeOffset> UpdateDate { get; set; }
    	public Nullable<short> ConcurrencyValue { get; set; }
    
    	public gcsEntity gcsEntity { get; set; }
    
    }
}
