//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

#if NetCoreApi
namespace GalaxySMS.Business.Entities.Api.NetCore
#elif NETSTANDARD2_0
namespace GalaxySMS.Business.Entities.NetStd2
#else
namespace GalaxySMS.Business.Entities
#endif
{
    using System;
    using System.Collections.Generic;
    using GCS.Core.Common.Contracts;
	using GCS.Core.Common.Core;
    public partial class GalaxyPanel : EntityBase, IIdentifiableEntity, IEquatable<GalaxyPanel>, ITableEntityBase
    {
    /*	// Move to partial class
    using System;
    using System.Collections.Generic;
    using GCS.Core.Common.Contracts;
	using GCS.Core.Common.Core;
    using GCS.Core.Common.Extensions;
    
    using System.Runtime.Serialization;
    
    #if NetCoreApi
    namespace GalaxySMS.Business.Entities.Api.NetCore
    #elif NETSTANDARD2_0
    namespace GalaxySMS.Business.Entities.NetStd2
    #else
    namespace GalaxySMS.Business.Entities
    #endif
    {
        public partial class GalaxyPanel
        {
        	public GalaxyPanel()
        	{
        		Initialize();
        	}
        
        	public GalaxyPanel(GalaxyPanel e)
        	{
        		Initialize(e);
        	}
        
        	public void Initialize()
        	{
        		this.GalaxyPanelSites = new HashSet<GalaxyPanelSite>();
        		this.GalaxyCpus = new HashSet<GalaxyCpu>();
        		this.GalaxyPanelCommandAudits = new HashSet<GalaxyPanelCommandAudit>();
        		this.GalaxyPanelActivityEvents = new HashSet<GalaxyPanelActivityEvent>();
        	}
        
        	public void Initialize(GalaxyPanel e)
        	{
        		Initialize();
        		if( e == null )
        			return;
        
        		this.IsDirty = e.IsDirty;
        		this.GalaxyPanelUid = e.GalaxyPanelUid;
        		this.ClusterUid = e.ClusterUid;
        		this.PanelNumber = e.PanelNumber;
        		this.PanelName = e.PanelName;
        		this.Location = e.Location;
        		this.InsertName = e.InsertName;
        		this.InsertDate = e.InsertDate;
        		this.UpdateName = e.UpdateName;
        		this.UpdateDate = e.UpdateDate;
        		this.ConcurrencyValue = e.ConcurrencyValue;
        		this.GalaxyPanelModelUid = e.GalaxyPanelModelUid;
        		this.AlertEventsFlag = e.AlertEventsFlag;
        		this.GalaxyPanelSites = e.GalaxyPanelSites.ToCollection();
        		this.GalaxyCpus = e.GalaxyCpus.ToCollection();
        		this.GalaxyPanelCommandAudits = e.GalaxyPanelCommandAudits.ToCollection();
        		this.GalaxyPanelActivityEvents = e.GalaxyPanelActivityEvents.ToCollection();
        		
        	}
        
        	public bool IsAnythingDirty
        	{
        		get
        		{
        			//foreach( var o in InterfaceBoardSections)
        			//{
        			//	if (o.IsAnythingDirty == true)
        			//		return true;
        			//}
        			return IsDirty;                
        		}
        	}
        
        	public GalaxyPanel Clone(GalaxyPanel e)
        	{
        		return new GalaxyPanel(e);
        	}
        
        	public bool Equals(GalaxyPanel other)
        	{
        		return base.Equals(other);
        	}
        	
        	public bool IsPrimaryKeyEqual(GalaxyPanel other)
        	{
        		if( other == null ) 
        			return false;
        
        		if(other.GalaxyPanelUid != this.GalaxyPanelUid )
        			return false;
        		return true;
        	}
        
        	public override int GetHashCode()
        	{
        		return base.GetHashCode();
        	}
        
        	public override string ToString()
        	{
        		return base.ToString();
        	}
        }
    }
    */
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public System.Guid GalaxyPanelUid { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public System.Guid ClusterUid { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public short PanelNumber { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public string PanelName { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public string Location { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public string InsertName { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public Nullable<System.DateTime> InsertDate { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public string UpdateName { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public Nullable<System.DateTime> UpdateDate { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public Nullable<short> ConcurrencyValue { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public Nullable<System.Guid> GalaxyPanelModelUid { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public Nullable<int> AlertEventsFlag { get; set; }
    
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public GalaxyPanelModel GalaxyPanelModel { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public ICollection<GalaxyPanelSite> GalaxyPanelSites { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public ICollection<GalaxyCpu> GalaxyCpus { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public ICollection<GalaxyPanelCommandAudit> GalaxyPanelCommandAudits { get; set; }
    
    #if NetCoreApi
    #else
    	[DataMember]
    #endif
    	public ICollection<GalaxyPanelActivityEvent> GalaxyPanelActivityEvents { get; set; }
    
    }
}
