//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using GCS.Core.Common.Contracts;
using GCS.Core.Common.Core;
using System.Runtime.Serialization;

namespace GalaxySMS.Api.Models.RequestModels
{

    public partial class PersonClusterPermissionPutReq : PutRequestBase
    {

        public System.Guid PersonClusterPermissionUid { get; set; }

        //        public System.Guid PersonUid { get; set; }
        public System.Guid ClusterUid { get; set; }
        public Nullable<System.Guid> PersonCredentialUid { get; set; }
        //public string InsertName { get; set; }
        //public System.DateTimeOffset InsertDate { get; set; }
        //public string UpdateName { get; set; }
        //public Nullable<System.DateTimeOffset> UpdateDate { get; set; }
        //public Nullable<short> ConcurrencyValue { get; set; }
        public Nullable<System.Guid> CredentialClusterTourUid { get; set; }
        //public byte[] CredentialBits { get; set; }

        //public Cluster Cluster { get; set; }
        public ICollection<PersonAccessGroupPutReq> PersonAccessGroups { get; set; }
        public ICollection<PersonInputOutputGroupPutReq> PersonInputOutputGroups { get; set; }
        //public PersonCredential PersonCredential { get; set; }
        public PersonPersonalAccessGroupPutReq PersonPersonalAccessGroup { get; set; }

    }
}
