//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Client.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
	using GCS.Core.Common.Core;
	using GCS.Core.Common.Contracts;	using FluentValidation;
    public partial class CredentialH1030437Bit
    {
    	
    
    	class CredentialH1030437BitValidator : AbstractValidator<CredentialH1030437Bit>
    	{
    		public CredentialH1030437BitValidator()
    		{
    			//RuleFor(obj => obj.Description).NotEmpty();
    		}
    	}
    
    	protected override IValidator GetValidator()
    	{
    		return new CredentialH1030437BitValidator();
    	}
    }
    
}
