using System;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the AccessGroupLoadToCpu_CreatePDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class AccessGroupLoadToCpu_CreatePDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the AccessGroupLoadToCpu_CreatePDSA class
    /// </summary>
    public AccessGroupLoadToCpu_CreatePDSA() : base()
    {
      ClassName = "AccessGroupLoadToCpu_CreatePDSA";
    }
    #endregion
  }
}
