using System;
using System.Collections.Generic;
using System.Linq;


namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the AccessGroupEntityMapPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class.
  /// </summary>
  //[Serializable]
  public partial class AccessGroupEntityMapPDSA
  {
    #region Constructor
    /// <summary>
    /// Constructor for the AccessGroupEntityMapPDSA class
    /// </summary>
    public AccessGroupEntityMapPDSA() : base()
    {
      ClassName = "AccessGroupEntityMapPDSA";
    }
    #endregion

    #region RETURNVALUE property for Stored Procs
    private long _RETURNVALUE;

    /// <summary>
    /// Get/Set the RETURNVALUE from a stored procedure
    /// If you do not use Stored Procedures, feel free to comment this out
    /// </summary>
    public long RETURNVALUE
    {
      get { return _RETURNVALUE; }
      set
      {
        if (_RETURNVALUE != value)
        {
          _RETURNVALUE = value;
          RaisePropertyChanged("RETURNVALUE");
        }
      }
    }
    #endregion
        
    #region Override of ToString()
    /// <summary>
    /// Override the ToString() to display fields and field values.
    /// This helps when viewing Collection classes in Visual Studio
    /// </summary>
    /// <returns>A string with data from this class</returns>
    public override string ToString()
    {
      string ret = string.Empty;

      ret += "AccessGroupEntityMapUid: " + AccessGroupEntityMapUid.ToString() + " / ";
      ret += "InsertName: " + InsertName.ToString() + " / ";
      
      return ret;
    }
    #endregion
  }
  
  /// <summary>
  /// This class is used when you wish to create a collection of AccessGroupEntityMapPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  //[Serializable]
  public class AccessGroupEntityMapPDSACollection : List<AccessGroupEntityMapPDSA>
  {
    /// <summary>
    /// Find a AccessGroupEntityMapPDSA object
    /// </summary>
    /// <param name="accessGroupEntityMapUid">The Access Group Entity Map Uid to find</param>
    /// <returns>A AccessGroupEntityMapPDSA object</returns>
    public AccessGroupEntityMapPDSA GetAccessGroupEntityMapPDSA(Guid accessGroupEntityMapUid)
    {
      return Find(x => x.AccessGroupEntityMapUid == accessGroupEntityMapUid);
    }
    
    /// <summary>
    /// Get all AccessGroupEntityMapPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of AccessGroupEntityMapPDSA Objects</returns>
    public List<AccessGroupEntityMapPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<AccessGroupEntityMapPDSA>();
    }
        
    /// <summary>
    /// Get all AccessGroupEntityMapPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of AccessGroupEntityMapPDSA Objects where IsSelected=True</returns>
    public List<AccessGroupEntityMapPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<AccessGroupEntityMapPDSA>();
    }

  }
}
