using System;
using System.Collections.Generic;
using System.Linq;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA class
    /// </summary>
    public AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA() : base()
    {
      ClassName = "AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA";
    }
    #endregion
  }  
      
  /// <summary>
  /// This class is used when you wish to create a collection of AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSACollection : List<AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA>
  {
    
    /// <summary>
    /// Get all AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA Objects</returns>
    public List<AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA>();
    }
        
    /// <summary>
    /// Get all AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA Objects where IsSelected=True</returns>
    public List<AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<AcknowledgedAlarmBasicData_ByAccessPortalAlarmEventAcknowledgmentUidPDSA>();
    }

  }
}
