using System;
using System.Collections.Generic;
using System.Linq;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the ClusterUid_GetByInputDeviceUidPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class ClusterUid_GetByInputDeviceUidPDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the ClusterUid_GetByInputDeviceUidPDSA class
    /// </summary>
    public ClusterUid_GetByInputDeviceUidPDSA() : base()
    {
      ClassName = "ClusterUid_GetByInputDeviceUidPDSA";
    }
    #endregion
  }  
      
  /// <summary>
  /// This class is used when you wish to create a collection of ClusterUid_GetByInputDeviceUidPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class ClusterUid_GetByInputDeviceUidPDSACollection : List<ClusterUid_GetByInputDeviceUidPDSA>
  {
    
    /// <summary>
    /// Get all ClusterUid_GetByInputDeviceUidPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of ClusterUid_GetByInputDeviceUidPDSA Objects</returns>
    public List<ClusterUid_GetByInputDeviceUidPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<ClusterUid_GetByInputDeviceUidPDSA>();
    }
        
    /// <summary>
    /// Get all ClusterUid_GetByInputDeviceUidPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of ClusterUid_GetByInputDeviceUidPDSA Objects where IsSelected=True</returns>
    public List<ClusterUid_GetByInputDeviceUidPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<ClusterUid_GetByInputDeviceUidPDSA>();
    }

  }
}
