using System;
using System.Collections.Generic;
using System.Linq;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the ClusterPDSA_ByClusterNumberPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class ClusterPDSA_ByClusterNumberPDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the ClusterPDSA_ByClusterNumberPDSA class
    /// </summary>
    public ClusterPDSA_ByClusterNumberPDSA() : base()
    {
      ClassName = "ClusterPDSA_ByClusterNumberPDSA";
    }
    #endregion
  }  
      
  /// <summary>
  /// This class is used when you wish to create a collection of ClusterPDSA_ByClusterNumberPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class ClusterPDSA_ByClusterNumberPDSACollection : List<ClusterPDSA_ByClusterNumberPDSA>
  {
    
    /// <summary>
    /// Get all ClusterPDSA_ByClusterNumberPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of ClusterPDSA_ByClusterNumberPDSA Objects</returns>
    public List<ClusterPDSA_ByClusterNumberPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<ClusterPDSA_ByClusterNumberPDSA>();
    }
        
    /// <summary>
    /// Get all ClusterPDSA_ByClusterNumberPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of ClusterPDSA_ByClusterNumberPDSA Objects where IsSelected=True</returns>
    public List<ClusterPDSA_ByClusterNumberPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<ClusterPDSA_ByClusterNumberPDSA>();
    }

  }
}
