using System;
using System.Collections.Generic;
using System.Linq;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA
  {
    #region Constructor
    /// <summary>
    /// Constructor for the CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA class
    /// </summary>
    public CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA() : base()
    {
      ClassName = "CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA";
    }
    #endregion

  }  
    
  /// <summary>
  /// This class is used when you wish to create a collection of CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSACollection : List<CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA>
  {
    
    /// <summary>
    /// Get all CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA Objects</returns>
    public List<CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA>();
    }
        
    /// <summary>
    /// Get all CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA Objects where IsSelected=True</returns>
    public List<CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<CredentialToDeleteFromCpuPDSA_AllThatNeedDeletedPDSA>();
    }

  }
}
