using System;
using System.Collections.Generic;
using System.Linq;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the gcs_IsApplicationSettingUniquePDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class gcs_IsApplicationSettingUniquePDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the gcs_IsApplicationSettingUniquePDSA class
    /// </summary>
    public gcs_IsApplicationSettingUniquePDSA() : base()
    {
      ClassName = "gcs_IsApplicationSettingUniquePDSA";
    }
    #endregion
  }  
      
  /// <summary>
  /// This class is used when you wish to create a collection of gcs_IsApplicationSettingUniquePDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  //[Serializable]
  public class gcs_IsApplicationSettingUniquePDSACollection : List<gcs_IsApplicationSettingUniquePDSA>
  {
    
    /// <summary>
    /// Get all gcs_IsApplicationSettingUniquePDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of gcs_IsApplicationSettingUniquePDSA Objects</returns>
    public List<gcs_IsApplicationSettingUniquePDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<gcs_IsApplicationSettingUniquePDSA>();
    }
        
    /// <summary>
    /// Get all gcs_IsApplicationSettingUniquePDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of gcs_IsApplicationSettingUniquePDSA Objects where IsSelected=True</returns>
    public List<gcs_IsApplicationSettingUniquePDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<gcs_IsApplicationSettingUniquePDSA>();
    }

  }
}
