using System;
using System.Collections.Generic;
using System.Linq;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the gcsEntity_CanBeDeletedPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class gcsEntity_CanBeDeletedPDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the gcsEntity_CanBeDeletedPDSA class
    /// </summary>
    public gcsEntity_CanBeDeletedPDSA() : base()
    {
      ClassName = "gcsEntity_CanBeDeletedPDSA";
    }
    #endregion
  }  
      
  /// <summary>
  /// This class is used when you wish to create a collection of gcsEntity_CanBeDeletedPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class gcsEntity_CanBeDeletedPDSACollection : List<gcsEntity_CanBeDeletedPDSA>
  {
    
    /// <summary>
    /// Get all gcsEntity_CanBeDeletedPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of gcsEntity_CanBeDeletedPDSA Objects</returns>
    public List<gcsEntity_CanBeDeletedPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<gcsEntity_CanBeDeletedPDSA>();
    }
        
    /// <summary>
    /// Get all gcsEntity_CanBeDeletedPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of gcsEntity_CanBeDeletedPDSA Objects where IsSelected=True</returns>
    public List<gcsEntity_CanBeDeletedPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<gcsEntity_CanBeDeletedPDSA>();
    }

  }
}
