using System;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the gcsEntityCountPDSA_InsertTimePeriodCountPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class gcsEntityCountPDSA_InsertTimePeriodCountPDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the gcsEntityCountPDSA_InsertTimePeriodCountPDSA class
    /// </summary>
    public gcsEntityCountPDSA_InsertTimePeriodCountPDSA() : base()
    {
      ClassName = "gcsEntityCountPDSA_InsertTimePeriodCountPDSA";
    }
    #endregion
  }
}
