using System;
using System.Collections.Generic;
using System.Linq;


namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the gcsSettingPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class.
  /// </summary>
  //[Serializable]
  public partial class gcsSettingPDSA
  {
    #region Constructor
    /// <summary>
    /// Constructor for the gcsSettingPDSA class
    /// </summary>
    public gcsSettingPDSA() : base()
    {
      ClassName = "gcsSettingPDSA";
    }
    #endregion

    #region RETURNVALUE property for Stored Procs
    private long _RETURNVALUE;

    /// <summary>
    /// Get/Set the RETURNVALUE from a stored procedure
    /// If you do not use Stored Procedures, feel free to comment this out
    /// </summary>
    public long RETURNVALUE
    {
      get { return _RETURNVALUE; }
      set
      {
        if (_RETURNVALUE != value)
        {
          _RETURNVALUE = value;
          RaisePropertyChanged("RETURNVALUE");
        }
      }
    }
    #endregion
        
    #region Override of ToString()
    /// <summary>
    /// Override the ToString() to display fields and field values.
    /// This helps when viewing Collection classes in Visual Studio
    /// </summary>
    /// <returns>A string with data from this class</returns>
    public override string ToString()
    {
      string ret = string.Empty;

      ret += "SettingId: " + SettingId.ToString() + " / ";
      ret += "SettingGroup: " + SettingGroup.ToString() + " / ";
      
      return ret;
    }
    #endregion
  }
  
  /// <summary>
  /// This class is used when you wish to create a collection of gcsSettingPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class gcsSettingPDSACollection : List<gcsSettingPDSA>
  {
    /// <summary>
    /// Find a gcsSettingPDSA object
    /// </summary>
    /// <param name="settingId">The Setting Id to find</param>
    /// <returns>A gcsSettingPDSA object</returns>
    public gcsSettingPDSA GetgcsSettingPDSA(Guid settingId)
    {
      return Find(x => x.SettingId == settingId);
    }
    
    /// <summary>
    /// Get all gcsSettingPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of gcsSettingPDSA Objects</returns>
    public List<gcsSettingPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<gcsSettingPDSA>();
    }
        
    /// <summary>
    /// Get all gcsSettingPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of gcsSettingPDSA Objects where IsSelected=True</returns>
    public List<gcsSettingPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<gcsSettingPDSA>();
    }

  }
}
