using System;
using System.Collections.Generic;
using System.Linq;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the gcsSetting_GetValuePDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class gcsSetting_GetValuePDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the gcsSetting_GetValuePDSA class
    /// </summary>
    public gcsSetting_GetValuePDSA() : base()
    {
      ClassName = "gcsSetting_GetValuePDSA";
    }
    #endregion
  }  
      
  /// <summary>
  /// This class is used when you wish to create a collection of gcsSetting_GetValuePDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  //[Serializable]
  public class gcsSetting_GetValuePDSACollection : List<gcsSetting_GetValuePDSA>
  {
    
    /// <summary>
    /// Get all gcsSetting_GetValuePDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of gcsSetting_GetValuePDSA Objects</returns>
    public List<gcsSetting_GetValuePDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<gcsSetting_GetValuePDSA>();
    }
        
    /// <summary>
    /// Get all gcsSetting_GetValuePDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of gcsSetting_GetValuePDSA Objects where IsSelected=True</returns>
    public List<gcsSetting_GetValuePDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<gcsSetting_GetValuePDSA>();
    }

  }
}
