using System;
using System.Collections.Generic;
using System.Linq;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the GetEntityIdForAssaDayPeriodPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class GetEntityIdForAssaDayPeriodPDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the GetEntityIdForAssaDayPeriodPDSA class
    /// </summary>
    public GetEntityIdForAssaDayPeriodPDSA() : base()
    {
      ClassName = "GetEntityIdForAssaDayPeriodPDSA";
    }
    #endregion
  }  
      
  /// <summary>
  /// This class is used when you wish to create a collection of GetEntityIdForAssaDayPeriodPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class GetEntityIdForAssaDayPeriodPDSACollection : List<GetEntityIdForAssaDayPeriodPDSA>
  {
    
    /// <summary>
    /// Get all GetEntityIdForAssaDayPeriodPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of GetEntityIdForAssaDayPeriodPDSA Objects</returns>
    public List<GetEntityIdForAssaDayPeriodPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<GetEntityIdForAssaDayPeriodPDSA>();
    }
        
    /// <summary>
    /// Get all GetEntityIdForAssaDayPeriodPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of GetEntityIdForAssaDayPeriodPDSA Objects where IsSelected=True</returns>
    public List<GetEntityIdForAssaDayPeriodPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<GetEntityIdForAssaDayPeriodPDSA>();
    }

  }
}
