using System;
using System.Collections.Generic;
using System.Linq;


namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the InputDeviceGalaxyHardwareAddressPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class.
  /// </summary>
  //[Serializable]
  public partial class InputDeviceGalaxyHardwareAddressPDSA
  {
    #region Constructor
    /// <summary>
    /// Constructor for the InputDeviceGalaxyHardwareAddressPDSA class
    /// </summary>
    public InputDeviceGalaxyHardwareAddressPDSA() : base()
    {
      ClassName = "InputDeviceGalaxyHardwareAddressPDSA";
    }
    #endregion

    #region RETURNVALUE property for Stored Procs
    private long _RETURNVALUE;

    /// <summary>
    /// Get/Set the RETURNVALUE from a stored procedure
    /// If you do not use Stored Procedures, feel free to comment this out
    /// </summary>
    public long RETURNVALUE
    {
      get { return _RETURNVALUE; }
      set
      {
        if (_RETURNVALUE != value)
        {
          _RETURNVALUE = value;
          RaisePropertyChanged("RETURNVALUE");
        }
      }
    }
    #endregion
        
    #region Override of ToString()
    /// <summary>
    /// Override the ToString() to display fields and field values.
    /// This helps when viewing Collection classes in Visual Studio
    /// </summary>
    /// <returns>A string with data from this class</returns>
    public override string ToString()
    {
      string ret = string.Empty;

      ret += "InputDeviceGalaxyHardwareAddressUid: " + InputDeviceGalaxyHardwareAddressUid.ToString() + " / ";
      ret += "InsertName: " + InsertName.ToString() + " / ";
      
      return ret;
    }
    #endregion
  }
  
  /// <summary>
  /// This class is used when you wish to create a collection of InputDeviceGalaxyHardwareAddressPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class InputDeviceGalaxyHardwareAddressPDSACollection : List<InputDeviceGalaxyHardwareAddressPDSA>
  {
    /// <summary>
    /// Find a InputDeviceGalaxyHardwareAddressPDSA object
    /// </summary>
    /// <param name="inputDeviceGalaxyHardwareAddressUid">The Input Device Galaxy Hardware Address Uid to find</param>
    /// <returns>A InputDeviceGalaxyHardwareAddressPDSA object</returns>
    public InputDeviceGalaxyHardwareAddressPDSA GetInputDeviceGalaxyHardwareAddressPDSA(Guid inputDeviceGalaxyHardwareAddressUid)
    {
      return Find(x => x.InputDeviceGalaxyHardwareAddressUid == inputDeviceGalaxyHardwareAddressUid);
    }
    
    /// <summary>
    /// Get all InputDeviceGalaxyHardwareAddressPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of InputDeviceGalaxyHardwareAddressPDSA Objects</returns>
    public List<InputDeviceGalaxyHardwareAddressPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<InputDeviceGalaxyHardwareAddressPDSA>();
    }
        
    /// <summary>
    /// Get all InputDeviceGalaxyHardwareAddressPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of InputDeviceGalaxyHardwareAddressPDSA Objects where IsSelected=True</returns>
    public List<InputDeviceGalaxyHardwareAddressPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<InputDeviceGalaxyHardwareAddressPDSA>();
    }

  }
}
