using System;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the insert_OutputDeviceActivityEventPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class insert_OutputDeviceActivityEventPDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the insert_OutputDeviceActivityEventPDSA class
    /// </summary>
    public insert_OutputDeviceActivityEventPDSA() : base()
    {
      ClassName = "insert_OutputDeviceActivityEventPDSA";
    }
    #endregion
  }
}
