using System;
using System.Collections.Generic;
using System.Linq;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the IsAccessPortalAuxiliaryOutputModeUniquePDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class IsAccessPortalAuxiliaryOutputModeUniquePDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the IsAccessPortalAuxiliaryOutputModeUniquePDSA class
    /// </summary>
    public IsAccessPortalAuxiliaryOutputModeUniquePDSA() : base()
    {
      ClassName = "IsAccessPortalAuxiliaryOutputModeUniquePDSA";
    }
    #endregion
  }  
      
  /// <summary>
  /// This class is used when you wish to create a collection of IsAccessPortalAuxiliaryOutputModeUniquePDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  //[Serializable]
  public class IsAccessPortalAuxiliaryOutputModeUniquePDSACollection : List<IsAccessPortalAuxiliaryOutputModeUniquePDSA>
  {
    
    /// <summary>
    /// Get all IsAccessPortalAuxiliaryOutputModeUniquePDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of IsAccessPortalAuxiliaryOutputModeUniquePDSA Objects</returns>
    public List<IsAccessPortalAuxiliaryOutputModeUniquePDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<IsAccessPortalAuxiliaryOutputModeUniquePDSA>();
    }
        
    /// <summary>
    /// Get all IsAccessPortalAuxiliaryOutputModeUniquePDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of IsAccessPortalAuxiliaryOutputModeUniquePDSA Objects where IsSelected=True</returns>
    public List<IsAccessPortalAuxiliaryOutputModeUniquePDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<IsAccessPortalAuxiliaryOutputModeUniquePDSA>();
    }

  }
}
