using System;
using System.Collections.Generic;
using System.Linq;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the IsGalaxyInputArmingInputOutputGroupUniquePDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class IsGalaxyInputArmingInputOutputGroupUniquePDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the IsGalaxyInputArmingInputOutputGroupUniquePDSA class
    /// </summary>
    public IsGalaxyInputArmingInputOutputGroupUniquePDSA() : base()
    {
      ClassName = "IsGalaxyInputArmingInputOutputGroupUniquePDSA";
    }
    #endregion
  }  
      
  /// <summary>
  /// This class is used when you wish to create a collection of IsGalaxyInputArmingInputOutputGroupUniquePDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class IsGalaxyInputArmingInputOutputGroupUniquePDSACollection : List<IsGalaxyInputArmingInputOutputGroupUniquePDSA>
  {
    
    /// <summary>
    /// Get all IsGalaxyInputArmingInputOutputGroupUniquePDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of IsGalaxyInputArmingInputOutputGroupUniquePDSA Objects</returns>
    public List<IsGalaxyInputArmingInputOutputGroupUniquePDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<IsGalaxyInputArmingInputOutputGroupUniquePDSA>();
    }
        
    /// <summary>
    /// Get all IsGalaxyInputArmingInputOutputGroupUniquePDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of IsGalaxyInputArmingInputOutputGroupUniquePDSA Objects where IsSelected=True</returns>
    public List<IsGalaxyInputArmingInputOutputGroupUniquePDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<IsGalaxyInputArmingInputOutputGroupUniquePDSA>();
    }

  }
}
