using System;
using System.Collections.Generic;
using System.Linq;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the IsInputOutputGroupValidForGalaxyPanelPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class IsInputOutputGroupValidForGalaxyPanelPDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the IsInputOutputGroupValidForGalaxyPanelPDSA class
    /// </summary>
    public IsInputOutputGroupValidForGalaxyPanelPDSA() : base()
    {
      ClassName = "IsInputOutputGroupValidForGalaxyPanelPDSA";
    }
    #endregion
  }  
      
  /// <summary>
  /// This class is used when you wish to create a collection of IsInputOutputGroupValidForGalaxyPanelPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class IsInputOutputGroupValidForGalaxyPanelPDSACollection : List<IsInputOutputGroupValidForGalaxyPanelPDSA>
  {
    
    /// <summary>
    /// Get all IsInputOutputGroupValidForGalaxyPanelPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of IsInputOutputGroupValidForGalaxyPanelPDSA Objects</returns>
    public List<IsInputOutputGroupValidForGalaxyPanelPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<IsInputOutputGroupValidForGalaxyPanelPDSA>();
    }
        
    /// <summary>
    /// Get all IsInputOutputGroupValidForGalaxyPanelPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of IsInputOutputGroupValidForGalaxyPanelPDSA Objects where IsSelected=True</returns>
    public List<IsInputOutputGroupValidForGalaxyPanelPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<IsInputOutputGroupValidForGalaxyPanelPDSA>();
    }

  }
}
