using System;
using System.Collections.Generic;
using System.Linq;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the OutputDevicePDSA_GetNamesForSiteUidPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class OutputDevicePDSA_GetNamesForSiteUidPDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the OutputDevicePDSA_GetNamesForSiteUidPDSA class
    /// </summary>
    public OutputDevicePDSA_GetNamesForSiteUidPDSA() : base()
    {
      ClassName = "OutputDevicePDSA_GetNamesForSiteUidPDSA";
    }
    #endregion
  }  
      
  /// <summary>
  /// This class is used when you wish to create a collection of OutputDevicePDSA_GetNamesForSiteUidPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class OutputDevicePDSA_GetNamesForSiteUidPDSACollection : List<OutputDevicePDSA_GetNamesForSiteUidPDSA>
  {
    
    /// <summary>
    /// Get all OutputDevicePDSA_GetNamesForSiteUidPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of OutputDevicePDSA_GetNamesForSiteUidPDSA Objects</returns>
    public List<OutputDevicePDSA_GetNamesForSiteUidPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<OutputDevicePDSA_GetNamesForSiteUidPDSA>();
    }
        
    /// <summary>
    /// Get all OutputDevicePDSA_GetNamesForSiteUidPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of OutputDevicePDSA_GetNamesForSiteUidPDSA Objects where IsSelected=True</returns>
    public List<OutputDevicePDSA_GetNamesForSiteUidPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<OutputDevicePDSA_GetNamesForSiteUidPDSA>();
    }

  }
}
