using System;
using System.Collections.Generic;
using System.Linq;


namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the OutputDeviceActivityEventPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class.
  /// </summary>
  //[Serializable]
  public partial class OutputDeviceActivityEventPDSA
  {
    #region Constructor
    /// <summary>
    /// Constructor for the OutputDeviceActivityEventPDSA class
    /// </summary>
    public OutputDeviceActivityEventPDSA() : base()
    {
      ClassName = "OutputDeviceActivityEventPDSA";
    }
    #endregion

    #region RETURNVALUE property for Stored Procs
    private long _RETURNVALUE;

    /// <summary>
    /// Get/Set the RETURNVALUE from a stored procedure
    /// If you do not use Stored Procedures, feel free to comment this out
    /// </summary>
    public long RETURNVALUE
    {
      get { return _RETURNVALUE; }
      set
      {
        if (_RETURNVALUE != value)
        {
          _RETURNVALUE = value;
          RaisePropertyChanged("RETURNVALUE");
        }
      }
    }
    #endregion
        
    #region Override of ToString()
    /// <summary>
    /// Override the ToString() to display fields and field values.
    /// This helps when viewing Collection classes in Visual Studio
    /// </summary>
    /// <returns>A string with data from this class</returns>
    public override string ToString()
    {
      string ret = string.Empty;

      ret += "OutputDeviceActivityEventUid: " + OutputDeviceActivityEventUid.ToString() + " / ";
      ret += "OutputDeviceActivityEventUid: " + OutputDeviceActivityEventUid.ToString() + " / ";
      
      return ret;
    }
    #endregion
  }
  
  /// <summary>
  /// This class is used when you wish to create a collection of OutputDeviceActivityEventPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class OutputDeviceActivityEventPDSACollection : List<OutputDeviceActivityEventPDSA>
  {
    /// <summary>
    /// Find a OutputDeviceActivityEventPDSA object
    /// </summary>
    /// <param name="outputDeviceActivityEventUid">The Output Device Activity Event Uid to find</param>
    /// <returns>A OutputDeviceActivityEventPDSA object</returns>
    public OutputDeviceActivityEventPDSA GetOutputDeviceActivityEventPDSA(Guid outputDeviceActivityEventUid)
    {
      return Find(x => x.OutputDeviceActivityEventUid == outputDeviceActivityEventUid);
    }
    
    /// <summary>
    /// Get all OutputDeviceActivityEventPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of OutputDeviceActivityEventPDSA Objects</returns>
    public List<OutputDeviceActivityEventPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<OutputDeviceActivityEventPDSA>();
    }
        
    /// <summary>
    /// Get all OutputDeviceActivityEventPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of OutputDeviceActivityEventPDSA Objects where IsSelected=True</returns>
    public List<OutputDeviceActivityEventPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<OutputDeviceActivityEventPDSA>();
    }

  }
}
