using System;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the OutputDeviceLoadToCpu_SaveLastLoadedDatePDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class OutputDeviceLoadToCpu_SaveLastLoadedDatePDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the OutputDeviceLoadToCpu_SaveLastLoadedDatePDSA class
    /// </summary>
    public OutputDeviceLoadToCpu_SaveLastLoadedDatePDSA() : base()
    {
      ClassName = "OutputDeviceLoadToCpu_SaveLastLoadedDatePDSA";
    }
    #endregion
  }
}
