using System;
using System.Collections.Generic;
using System.Linq;

using GalaxySMS.BusinessLayer;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the AssaAccessPointTypePDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class.
  /// </summary>
  //[Serializable]
  public partial class AssaAccessPointTypePDSA
  {
    #region Constructor
    /// <summary>
    /// Constructor for the AssaAccessPointTypePDSA class
    /// </summary>
    public AssaAccessPointTypePDSA() : base()
    {
      ClassName = "AssaAccessPointTypePDSA";
    }
    #endregion

    #region RETURNVALUE property for Stored Procs
    private long _RETURNVALUE;

    /// <summary>
    /// Get/Set the RETURNVALUE from a stored procedure
    /// If you do not use Stored Procedures, feel free to comment this out
    /// </summary>
    public long RETURNVALUE
    {
      get { return _RETURNVALUE; }
      set
      {
        if (_RETURNVALUE != value)
        {
          _RETURNVALUE = value;
          RaisePropertyChanged("RETURNVALUE");
        }
      }
    }
    #endregion
        
    #region Override of ToString()
    /// <summary>
    /// Override the ToString() to display fields and field values.
    /// This helps when viewing Collection classes in Visual Studio
    /// </summary>
    /// <returns>A string with data from this class</returns>
    public override string ToString()
    {
      string ret = string.Empty;

      ret += "AssaAccessPointTypeUid: " + AssaAccessPointTypeUid.ToString() + " / ";
      ret += "Id: " + Id.ToString() + " / ";
      
      return ret;
    }
    #endregion
  }
  
  /// <summary>
  /// This class is used when you wish to create a collection of AssaAccessPointTypePDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  //[Serializable]
  public class AssaAccessPointTypePDSACollection : List<AssaAccessPointTypePDSA>
  {
    /// <summary>
    /// Find a AssaAccessPointTypePDSA object
    /// </summary>
    /// <param name="assaAccessPointTypeUid">The Assa Access Point Type Uid to find</param>
    /// <returns>A AssaAccessPointTypePDSA object</returns>
    public AssaAccessPointTypePDSA GetAssaAccessPointTypePDSA(Guid assaAccessPointTypeUid)
    {
      return Find(x => x.AssaAccessPointTypeUid == assaAccessPointTypeUid);
    }
    
    /// <summary>
    /// Get all AssaAccessPointTypePDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of AssaAccessPointTypePDSA Objects</returns>
    public List<AssaAccessPointTypePDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<AssaAccessPointTypePDSA>();
    }
        
    /// <summary>
    /// Get all AssaAccessPointTypePDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of AssaAccessPointTypePDSA Objects where IsSelected=True</returns>
    public List<AssaAccessPointTypePDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<AssaAccessPointTypePDSA>();
    }

  }
}
