using System;
using System.Collections.Generic;
using System.Linq;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the ClusterUids_SelectForUserIdPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class ClusterUids_SelectForUserIdPDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the ClusterUids_SelectForUserIdPDSA class
    /// </summary>
    public ClusterUids_SelectForUserIdPDSA() : base()
    {
      ClassName = "ClusterUids_SelectForUserIdPDSA";
    }
    #endregion
  }  
      
  /// <summary>
  /// This class is used when you wish to create a collection of ClusterUids_SelectForUserIdPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class ClusterUids_SelectForUserIdPDSACollection : List<ClusterUids_SelectForUserIdPDSA>
  {
    
    /// <summary>
    /// Get all ClusterUids_SelectForUserIdPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of ClusterUids_SelectForUserIdPDSA Objects</returns>
    public List<ClusterUids_SelectForUserIdPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<ClusterUids_SelectForUserIdPDSA>();
    }
        
    /// <summary>
    /// Get all ClusterUids_SelectForUserIdPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of ClusterUids_SelectForUserIdPDSA Objects where IsSelected=True</returns>
    public List<ClusterUids_SelectForUserIdPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<ClusterUids_SelectForUserIdPDSA>();
    }

  }
}
