using System;
using System.Collections.Generic;
using System.Linq;


namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the CredentialXceedId40BitPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class.
  /// </summary>
  //[Serializable]
  public partial class CredentialXceedId40BitPDSA
  {
    #region Constructor
    /// <summary>
    /// Constructor for the CredentialXceedId40BitPDSA class
    /// </summary>
    public CredentialXceedId40BitPDSA() : base()
    {
      ClassName = "CredentialXceedId40BitPDSA";
    }
    #endregion

    #region RETURNVALUE property for Stored Procs
    private long _RETURNVALUE;

    /// <summary>
    /// Get/Set the RETURNVALUE from a stored procedure
    /// If you do not use Stored Procedures, feel free to comment this out
    /// </summary>
    public long RETURNVALUE
    {
      get { return _RETURNVALUE; }
      set
      {
        if (_RETURNVALUE != value)
        {
          _RETURNVALUE = value;
          RaisePropertyChanged("RETURNVALUE");
        }
      }
    }
    #endregion
        
    #region Override of ToString()
    /// <summary>
    /// Override the ToString() to display fields and field values.
    /// This helps when viewing Collection classes in Visual Studio
    /// </summary>
    /// <returns>A string with data from this class</returns>
    public override string ToString()
    {
      string ret = string.Empty;

      ret += "CredentialUid: " + CredentialUid.ToString() + " / ";
      ret += "InsertName: " + InsertName.ToString() + " / ";
      
      return ret;
    }
    #endregion
  }
  
  /// <summary>
  /// This class is used when you wish to create a collection of CredentialXceedId40BitPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class CredentialXceedId40BitPDSACollection : List<CredentialXceedId40BitPDSA>
  {
    /// <summary>
    /// Find a CredentialXceedId40BitPDSA object
    /// </summary>
    /// <param name="credentialUid">The Credential Uid to find</param>
    /// <returns>A CredentialXceedId40BitPDSA object</returns>
    public CredentialXceedId40BitPDSA GetCredentialXceedId40BitPDSA(Guid credentialUid)
    {
      return Find(x => x.CredentialUid == credentialUid);
    }
    
    /// <summary>
    /// Get all CredentialXceedId40BitPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of CredentialXceedId40BitPDSA Objects</returns>
    public List<CredentialXceedId40BitPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<CredentialXceedId40BitPDSA>();
    }
        
    /// <summary>
    /// Get all CredentialXceedId40BitPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of CredentialXceedId40BitPDSA Objects where IsSelected=True</returns>
    public List<CredentialXceedId40BitPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<CredentialXceedId40BitPDSA>();
    }

  }
}
