using System;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the gcsEntityCountPDSA_InsertPersonCountPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class gcsEntityCountPDSA_InsertPersonCountPDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the gcsEntityCountPDSA_InsertPersonCountPDSA class
    /// </summary>
    public gcsEntityCountPDSA_InsertPersonCountPDSA() : base()
    {
      ClassName = "gcsEntityCountPDSA_InsertPersonCountPDSA";
    }
    #endregion
  }
}
