using System;
using System.Collections.Generic;
using System.Linq;


namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the InputOutputGroupCommandAuditPDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class.
  /// </summary>
  //[Serializable]
  public partial class InputOutputGroupCommandAuditPDSA
  {
    #region Constructor
    /// <summary>
    /// Constructor for the InputOutputGroupCommandAuditPDSA class
    /// </summary>
    public InputOutputGroupCommandAuditPDSA() : base()
    {
      ClassName = "InputOutputGroupCommandAuditPDSA";
    }
    #endregion

    #region RETURNVALUE property for Stored Procs
    private long _RETURNVALUE;

    /// <summary>
    /// Get/Set the RETURNVALUE from a stored procedure
    /// If you do not use Stored Procedures, feel free to comment this out
    /// </summary>
    public long RETURNVALUE
    {
      get { return _RETURNVALUE; }
      set
      {
        if (_RETURNVALUE != value)
        {
          _RETURNVALUE = value;
          RaisePropertyChanged("RETURNVALUE");
        }
      }
    }
    #endregion
        
    #region Override of ToString()
    /// <summary>
    /// Override the ToString() to display fields and field values.
    /// This helps when viewing Collection classes in Visual Studio
    /// </summary>
    /// <returns>A string with data from this class</returns>
    public override string ToString()
    {
      string ret = string.Empty;

      ret += "InputOutputGroupCommandAuditUid: " + InputOutputGroupCommandAuditUid.ToString() + " / ";
      ret += "InsertName: " + InsertName.ToString() + " / ";
      
      return ret;
    }
    #endregion
  }
  
  /// <summary>
  /// This class is used when you wish to create a collection of InputOutputGroupCommandAuditPDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  public class InputOutputGroupCommandAuditPDSACollection : List<InputOutputGroupCommandAuditPDSA>
  {
    /// <summary>
    /// Find a InputOutputGroupCommandAuditPDSA object
    /// </summary>
    /// <param name="inputOutputGroupCommandAuditUid">The Input Output Group Command Audit Uid to find</param>
    /// <returns>A InputOutputGroupCommandAuditPDSA object</returns>
    public InputOutputGroupCommandAuditPDSA GetInputOutputGroupCommandAuditPDSA(Guid inputOutputGroupCommandAuditUid)
    {
      return Find(x => x.InputOutputGroupCommandAuditUid == inputOutputGroupCommandAuditUid);
    }
    
    /// <summary>
    /// Get all InputOutputGroupCommandAuditPDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of InputOutputGroupCommandAuditPDSA Objects</returns>
    public List<InputOutputGroupCommandAuditPDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<InputOutputGroupCommandAuditPDSA>();
    }
        
    /// <summary>
    /// Get all InputOutputGroupCommandAuditPDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of InputOutputGroupCommandAuditPDSA Objects where IsSelected=True</returns>
    public List<InputOutputGroupCommandAuditPDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<InputOutputGroupCommandAuditPDSA>();
    }

  }
}
