using System;
using System.Collections.Generic;
using System.Linq;

using PDSA.Validation;

namespace GalaxySMS.EntityLayer
{
  /// <summary>
  /// This class is an extension of the IsGalaxyPanelUniquePDSA Entity class
  /// This class is generated by the Haystack Code Generator for .NET.
  /// You may add additional properties to this class. 
  /// </summary>
  //[Serializable]
  public partial class IsGalaxyPanelUniquePDSA : PDSAEntityBase
  {
    #region Constructor
    /// <summary>
    /// Constructor for the IsGalaxyPanelUniquePDSA class
    /// </summary>
    public IsGalaxyPanelUniquePDSA() : base()
    {
      ClassName = "IsGalaxyPanelUniquePDSA";
    }
    #endregion
  }  
      
  /// <summary>
  /// This class is used when you wish to create a collection of IsGalaxyPanelUniquePDSA classes.
  /// You may add additional methods to this class.
  /// </summary>
  //[Serializable]
  public class IsGalaxyPanelUniquePDSACollection : List<IsGalaxyPanelUniquePDSA>
  {
    
    /// <summary>
    /// Get all IsGalaxyPanelUniquePDSA objects where IsDirty=True
    /// </summary>
    /// <returns>A List of IsGalaxyPanelUniquePDSA Objects</returns>
    public List<IsGalaxyPanelUniquePDSA> GetChanged()
    {
      return (from item in this
              where item.IsDirty == true
              select item).ToList<IsGalaxyPanelUniquePDSA>();
    }
        
    /// <summary>
    /// Get all IsGalaxyPanelUniquePDSA objects where IsSelected=True
    /// </summary>
    /// <returns>A List of IsGalaxyPanelUniquePDSA Objects where IsSelected=True</returns>
    public List<IsGalaxyPanelUniquePDSA> GetSelected()
    {
      return (from item in this
              where item.IsSelected == true
              select item).ToList<IsGalaxyPanelUniquePDSA>();
    }

  }
}
