//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using GCS.Core.Common.Contracts;
using GCS.Core.Common.Core;
using System.Runtime.Serialization;

namespace GalaxySMS.Client.Entities
{
    [DataContract]
    public partial class ClusterTypeClusterCommandBasic : EntityBaseSimple
    {

        [DataMember]
        public System.Guid ClusterTypeClusterCommandUid { get; set; }

        [DataMember]
        public System.Guid ClusterTypeUid { get; set; }

        [DataMember]
        public System.Guid ClusterCommandUid { get; set; }
    }
}
