//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Client.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
	using GCS.Core.Common.Core;
	using GCS.Core.Common.Contracts;	using FluentValidation;
    
	[DataContract]
	public partial class AccessPortalType : DbObjectBase, ITableEntityBase
    {
    
    /*	// Move to partial class
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
	using GCS.Core.Common.Core;
	using GCS.Core.Common.Contracts;	using FluentValidation;
    using System.Collections.ObjectModel;
    using GCS.Core.Common.Extensions;
    
    namespace GalaxySMS.Client.Entities
    {
        public partial class AccessPortalType
        {
        	public AccessPortalType() : base()
        	{
        		Initialize();
        	}
        
        	public AccessPortalType(AccessPortalType e) : base(e)
        	{
        		Initialize(e);
        	}
        
        	public void Initialize()
        	{
        		base.Initialize();
        		this.AccessPortalTypeAccessPortalCommands = new HashSet<AccessPortalTypeAccessPortalCommand>();
        }
        
        	public void Initialize(AccessPortalType e)
        	{
        		Initialize();
        		base.Initialize(e);
        
        		if( e == null )
        			return;
        		this.AccessPortalTypeUid = e.AccessPortalTypeUid;
        		this.CredentialReaderTypeUid = e.CredentialReaderTypeUid;
        		this.BinaryResourceUid = e.BinaryResourceUid;
        		this.AccessPortalTypeDescription = e.AccessPortalTypeDescription;
        		this.InsertName = e.InsertName;
        		this.InsertDate = e.InsertDate;
        		this.UpdateName = e.UpdateName;
        		this.UpdateDate = e.UpdateDate;
        		this.ConcurrencyValue = e.ConcurrencyValue;
        		this.AccessPortalTypeAccessPortalCommands = e.AccessPortalTypeAccessPortalCommands.ToCollection();
        		
        	}
        
        	public AccessPortalType Clone(AccessPortalType e)
        	{
        		return new AccessPortalType(e);
        	}
        
        	public bool Equals(AccessPortalType other)
        	{
        		return base.Equals(other);
        	}
        	
        	public bool IsPrimaryKeyEqual(AccessPortalType other)
        	{
        		if( other == null ) 
        			return false;
        
        		if(other.AccessPortalTypeUid != this.AccessPortalTypeUid )
        			return false;
        		return true;
        	}
        
        	public override int GetHashCode()
        	{
        		return base.GetHashCode();
        	}
        
        	public override string ToString()
        	{
        		return base.ToString();
        	}
        }
    }
    */
    
    	
    	private System.Guid _accessPortalTypeUid;
    
    	[DataMember]
    	public System.Guid AccessPortalTypeUid
    	{ 
    		get { return _accessPortalTypeUid; }
    		set
    		{
    			if (_accessPortalTypeUid != value )
    			{
    				_accessPortalTypeUid = value;
    				OnPropertyChanged(() => AccessPortalTypeUid);
    			}
    		}
    	}
    	
    	private System.Guid _credentialReaderTypeUid;
    
    	[DataMember]
    	public System.Guid CredentialReaderTypeUid
    	{ 
    		get { return _credentialReaderTypeUid; }
    		set
    		{
    			if (_credentialReaderTypeUid != value )
    			{
    				_credentialReaderTypeUid = value;
    				OnPropertyChanged(() => CredentialReaderTypeUid);
    			}
    		}
    	}
    	
    	private Nullable<System.Guid> _binaryResourceUid;
    
    	[DataMember]
    	public Nullable<System.Guid> BinaryResourceUid
    	{ 
    		get { return _binaryResourceUid; }
    		set
    		{
    			if (_binaryResourceUid != value )
    			{
    				_binaryResourceUid = value;
    				OnPropertyChanged(() => BinaryResourceUid);
    			}
    		}
    	}
    	
    	private string _accessPortalTypeDescription;
    
    	[DataMember]
    	public string AccessPortalTypeDescription
    	{ 
    		get { return _accessPortalTypeDescription; }
    		set
    		{
    			if (_accessPortalTypeDescription != value )
    			{
    				_accessPortalTypeDescription = value;
    				OnPropertyChanged(() => AccessPortalTypeDescription);
    			}
    		}
    	}
    	
    	private string _insertName;
    
    	[DataMember]
    	public string InsertName
    	{ 
    		get { return _insertName; }
    		set
    		{
    			if (_insertName != value )
    			{
    				_insertName = value;
    				OnPropertyChanged(() => InsertName);
    			}
    		}
    	}
    	
    	private Nullable<System.DateTime> _insertDate;
    
    	[DataMember]
    	public Nullable<System.DateTime> InsertDate
    	{ 
    		get { return _insertDate; }
    		set
    		{
    			if (_insertDate != value )
    			{
    				_insertDate = value;
    				OnPropertyChanged(() => InsertDate);
    			}
    		}
    	}
    	
    	private string _updateName;
    
    	[DataMember]
    	public string UpdateName
    	{ 
    		get { return _updateName; }
    		set
    		{
    			if (_updateName != value )
    			{
    				_updateName = value;
    				OnPropertyChanged(() => UpdateName);
    			}
    		}
    	}
    	
    	private Nullable<System.DateTime> _updateDate;
    
    	[DataMember]
    	public Nullable<System.DateTime> UpdateDate
    	{ 
    		get { return _updateDate; }
    		set
    		{
    			if (_updateDate != value )
    			{
    				_updateDate = value;
    				OnPropertyChanged(() => UpdateDate);
    			}
    		}
    	}
    	
    	private Nullable<short> _concurrencyValue;
    
    	[DataMember]
    	public Nullable<short> ConcurrencyValue
    	{ 
    		get { return _concurrencyValue; }
    		set
    		{
    			if (_concurrencyValue != value )
    			{
    				_concurrencyValue = value;
    				OnPropertyChanged(() => ConcurrencyValue);
    			}
    		}
    	}
    
    	
    	private gcsBinaryResource _gcsBinaryResource;
    
    	[DataMember]
    	public virtual gcsBinaryResource gcsBinaryResource
    	{ 
    		get { return _gcsBinaryResource; }
    		set
    		{
    			if (_gcsBinaryResource != value )
    			{
    				_gcsBinaryResource = value;
    				OnPropertyChanged(() => gcsBinaryResource);
    			}
    		}
    	}
    	
    	private ICollection<AccessPortalTypeAccessPortalCommand> _accessPortalTypeAccessPortalCommands;
    
    	[DataMember]
    	public virtual ICollection<AccessPortalTypeAccessPortalCommand> AccessPortalTypeAccessPortalCommands
    	{ 
    		get { return _accessPortalTypeAccessPortalCommands; }
    		set
    		{
    			if (_accessPortalTypeAccessPortalCommands != value )
    			{
    				_accessPortalTypeAccessPortalCommands = value;
    				OnPropertyChanged(() => AccessPortalTypeAccessPortalCommands);
    			}
    		}
    	}
    }
    
}
