//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Client.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
	using GCS.Core.Common.Core;
	using GCS.Core.Common.Contracts;	using FluentValidation;
    
	[DataContract]
	public partial class AccessPortalCommandChoice : DbObjectBase, ITableEntityBase
    {
    
    /*	// Move to partial class
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
	using GCS.Core.Common.Core;
	using GCS.Core.Common.Contracts;	using FluentValidation;
    using System.Collections.ObjectModel;
    using GCS.Core.Common.Extensions;
    
    namespace GalaxySMS.Client.Entities
    {
        public partial class AccessPortalCommandChoice
        {
        	public AccessPortalCommandChoice() : base()
        	{
        		Initialize();
        	}
        
        	public AccessPortalCommandChoice(AccessPortalCommandChoice e) : base(e)
        	{
        		Initialize(e);
        	}
        
        	public void Initialize()
        	{
        		base.Initialize();
        }
        
        	public void Initialize(AccessPortalCommandChoice e)
        	{
        		Initialize();
        		base.Initialize(e);
        
        		if( e == null )
        			return;
        		this.AccessPortalCommandChoiceUid = e.AccessPortalCommandChoiceUid;
        		this.AccessPortalCommandUid = e.AccessPortalCommandUid;
        		this.Display = e.Display;
        		this.DisplayResourceKey = e.DisplayResourceKey;
        		this.Description = e.Description;
        		this.DescriptionResourceKey = e.DescriptionResourceKey;
        		this.ChoiceTypeCode = e.ChoiceTypeCode;
        		this.ApproxWaitTime = e.ApproxWaitTime;
        		this.InsertName = e.InsertName;
        		this.InsertDate = e.InsertDate;
        		this.UpdateName = e.UpdateName;
        		this.UpdateDate = e.UpdateDate;
        		this.ConcurrencyValue = e.ConcurrencyValue;
        		
        	}
        
        	public AccessPortalCommandChoice Clone(AccessPortalCommandChoice e)
        	{
        		return new AccessPortalCommandChoice(e);
        	}
        
        	public bool Equals(AccessPortalCommandChoice other)
        	{
        		return base.Equals(other);
        	}
        	
        	public bool IsPrimaryKeyEqual(AccessPortalCommandChoice other)
        	{
        		if( other == null ) 
        			return false;
        
        		if(other.AccessPortalCommandChoiceUid != this.AccessPortalCommandChoiceUid )
        			return false;
        		return true;
        	}
        
        	public override int GetHashCode()
        	{
        		return base.GetHashCode();
        	}
        
        	public override string ToString()
        	{
        		return base.ToString();
        	}
        }
    }
    */
    
    	
    	private System.Guid _accessPortalCommandChoiceUid;
    
    	[DataMember]
    	public System.Guid AccessPortalCommandChoiceUid
    	{ 
    		get { return _accessPortalCommandChoiceUid; }
    		set
    		{
    			if (_accessPortalCommandChoiceUid != value )
    			{
    				_accessPortalCommandChoiceUid = value;
    				OnPropertyChanged(() => AccessPortalCommandChoiceUid);
    			}
    		}
    	}
    	
    	private System.Guid _accessPortalCommandUid;
    
    	[DataMember]
    	public System.Guid AccessPortalCommandUid
    	{ 
    		get { return _accessPortalCommandUid; }
    		set
    		{
    			if (_accessPortalCommandUid != value )
    			{
    				_accessPortalCommandUid = value;
    				OnPropertyChanged(() => AccessPortalCommandUid);
    			}
    		}
    	}
    	
    	private string _display;
    
    	[DataMember]
    	public string Display
    	{ 
    		get { return _display; }
    		set
    		{
    			if (_display != value )
    			{
    				_display = value;
    				OnPropertyChanged(() => Display);
    			}
    		}
    	}
    	
    	private Nullable<System.Guid> _displayResourceKey;
    
    	[DataMember]
    	public Nullable<System.Guid> DisplayResourceKey
    	{ 
    		get { return _displayResourceKey; }
    		set
    		{
    			if (_displayResourceKey != value )
    			{
    				_displayResourceKey = value;
    				OnPropertyChanged(() => DisplayResourceKey);
    			}
    		}
    	}
    	
    	private string _description;
    
    	[DataMember]
    	public string Description
    	{ 
    		get { return _description; }
    		set
    		{
    			if (_description != value )
    			{
    				_description = value;
    				OnPropertyChanged(() => Description);
    			}
    		}
    	}
    	
    	private Nullable<System.Guid> _descriptionResourceKey;
    
    	[DataMember]
    	public Nullable<System.Guid> DescriptionResourceKey
    	{ 
    		get { return _descriptionResourceKey; }
    		set
    		{
    			if (_descriptionResourceKey != value )
    			{
    				_descriptionResourceKey = value;
    				OnPropertyChanged(() => DescriptionResourceKey);
    			}
    		}
    	}
    	
    	private int _choiceTypeCode;
    
    	[DataMember]
    	public int ChoiceTypeCode
    	{ 
    		get { return _choiceTypeCode; }
    		set
    		{
    			if (_choiceTypeCode != value )
    			{
    				_choiceTypeCode = value;
    				OnPropertyChanged(() => ChoiceTypeCode);
    			}
    		}
    	}
    	
    	private int _approxWaitTime;
    
    	[DataMember]
    	public int ApproxWaitTime
    	{ 
    		get { return _approxWaitTime; }
    		set
    		{
    			if (_approxWaitTime != value )
    			{
    				_approxWaitTime = value;
    				OnPropertyChanged(() => ApproxWaitTime);
    			}
    		}
    	}
    	
    	private string _insertName;
    
    	[DataMember]
    	public string InsertName
    	{ 
    		get { return _insertName; }
    		set
    		{
    			if (_insertName != value )
    			{
    				_insertName = value;
    				OnPropertyChanged(() => InsertName);
    			}
    		}
    	}
    	
    	private Nullable<System.DateTime> _insertDate;
    
    	[DataMember]
    	public Nullable<System.DateTime> InsertDate
    	{ 
    		get { return _insertDate; }
    		set
    		{
    			if (_insertDate != value )
    			{
    				_insertDate = value;
    				OnPropertyChanged(() => InsertDate);
    			}
    		}
    	}
    	
    	private string _updateName;
    
    	[DataMember]
    	public string UpdateName
    	{ 
    		get { return _updateName; }
    		set
    		{
    			if (_updateName != value )
    			{
    				_updateName = value;
    				OnPropertyChanged(() => UpdateName);
    			}
    		}
    	}
    	
    	private Nullable<System.DateTime> _updateDate;
    
    	[DataMember]
    	public Nullable<System.DateTime> UpdateDate
    	{ 
    		get { return _updateDate; }
    		set
    		{
    			if (_updateDate != value )
    			{
    				_updateDate = value;
    				OnPropertyChanged(() => UpdateDate);
    			}
    		}
    	}
    	
    	private Nullable<short> _concurrencyValue;
    
    	[DataMember]
    	public Nullable<short> ConcurrencyValue
    	{ 
    		get { return _concurrencyValue; }
    		set
    		{
    			if (_concurrencyValue != value )
    			{
    				_concurrencyValue = value;
    				OnPropertyChanged(() => ConcurrencyValue);
    			}
    		}
    	}
    
    	
    	private AccessPortalCommand _accessPortalCommand;
    
    	[DataMember]
    	public virtual AccessPortalCommand AccessPortalCommand
    	{ 
    		get { return _accessPortalCommand; }
    		set
    		{
    			if (_accessPortalCommand != value )
    			{
    				_accessPortalCommand = value;
    				OnPropertyChanged(() => AccessPortalCommand);
    			}
    		}
    	}
    	
    	private gcsResourceString _gcsResourceString;
    
    	[DataMember]
    	public virtual gcsResourceString gcsResourceString
    	{ 
    		get { return _gcsResourceString; }
    		set
    		{
    			if (_gcsResourceString != value )
    			{
    				_gcsResourceString = value;
    				OnPropertyChanged(() => gcsResourceString);
    			}
    		}
    	}
    }
    
}
