//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Client.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
	using GCS.Core.Common.Core;
	using GCS.Core.Common.Contracts;	using FluentValidation;
    
	[DataContract]
	public partial class InputOutputGroupCommandAudit : DbObjectBase, ITableEntityBase
    {
    
    /*	// Move to partial class
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
	using GCS.Core.Common.Core;
	using GCS.Core.Common.Contracts;	using FluentValidation;
    using System.Collections.ObjectModel;
    using GCS.Core.Common.Extensions;
    
    namespace GalaxySMS.Client.Entities
    {
        public partial class InputOutputGroupCommandAudit
        {
        	public InputOutputGroupCommandAudit() : base()
        	{
        		Initialize();
        	}
        
        	public InputOutputGroupCommandAudit(InputOutputGroupCommandAudit e) : base(e)
        	{
        		Initialize(e);
        	}
        
        	public void Initialize()
        	{
        		base.Initialize();
        }
        
        	public void Initialize(InputOutputGroupCommandAudit e)
        	{
        		Initialize();
        		base.Initialize(e);
        
        		if( e == null )
        			return;
        		this.InputOutputGroupCommandAuditUid = e.InputOutputGroupCommandAuditUid;
        		this.UserId = e.UserId;
        		this.InputOutputGroupCommandUid = e.InputOutputGroupCommandUid;
        		this.InputOutputGroupUid = e.InputOutputGroupUid;
        		this.InsertName = e.InsertName;
        		this.InsertDate = e.InsertDate;
        		this.UpdateName = e.UpdateName;
        		this.UpdateDate = e.UpdateDate;
        		this.ConcurrencyValue = e.ConcurrencyValue;
        		
        	}
        
        	public InputOutputGroupCommandAudit Clone(InputOutputGroupCommandAudit e)
        	{
        		return new InputOutputGroupCommandAudit(e);
        	}
        
        	public bool Equals(InputOutputGroupCommandAudit other)
        	{
        		return base.Equals(other);
        	}
        	
        	public bool IsPrimaryKeyEqual(InputOutputGroupCommandAudit other)
        	{
        		if( other == null ) 
        			return false;
        
        		if(other.InputOutputGroupCommandAuditUid != this.InputOutputGroupCommandAuditUid )
        			return false;
        		return true;
        	}
        
        	public override int GetHashCode()
        	{
        		return base.GetHashCode();
        	}
        
        	public override string ToString()
        	{
        		return base.ToString();
        	}
        }
    }
    */
    
    	
    	private System.Guid _inputOutputGroupCommandAuditUid;
    
    	[DataMember]
    	public System.Guid InputOutputGroupCommandAuditUid
    	{ 
    		get { return _inputOutputGroupCommandAuditUid; }
    		set
    		{
    			if (_inputOutputGroupCommandAuditUid != value )
    			{
    				_inputOutputGroupCommandAuditUid = value;
    				OnPropertyChanged(() => InputOutputGroupCommandAuditUid);
    			}
    		}
    	}
    	
    	private System.Guid _userId;
    
    	[DataMember]
    	public System.Guid UserId
    	{ 
    		get { return _userId; }
    		set
    		{
    			if (_userId != value )
    			{
    				_userId = value;
    				OnPropertyChanged(() => UserId);
    			}
    		}
    	}
    	
    	private System.Guid _inputOutputGroupCommandUid;
    
    	[DataMember]
    	public System.Guid InputOutputGroupCommandUid
    	{ 
    		get { return _inputOutputGroupCommandUid; }
    		set
    		{
    			if (_inputOutputGroupCommandUid != value )
    			{
    				_inputOutputGroupCommandUid = value;
    				OnPropertyChanged(() => InputOutputGroupCommandUid);
    			}
    		}
    	}
    	
    	private System.Guid _inputOutputGroupUid;
    
    	[DataMember]
    	public System.Guid InputOutputGroupUid
    	{ 
    		get { return _inputOutputGroupUid; }
    		set
    		{
    			if (_inputOutputGroupUid != value )
    			{
    				_inputOutputGroupUid = value;
    				OnPropertyChanged(() => InputOutputGroupUid);
    			}
    		}
    	}
    	
    	private string _insertName;
    
    	[DataMember]
    	public string InsertName
    	{ 
    		get { return _insertName; }
    		set
    		{
    			if (_insertName != value )
    			{
    				_insertName = value;
    				OnPropertyChanged(() => InsertName);
    			}
    		}
    	}
    	
    	private Nullable<System.DateTime> _insertDate;
    
    	[DataMember]
    	public Nullable<System.DateTime> InsertDate
    	{ 
    		get { return _insertDate; }
    		set
    		{
    			if (_insertDate != value )
    			{
    				_insertDate = value;
    				OnPropertyChanged(() => InsertDate);
    			}
    		}
    	}
    	
    	private string _updateName;
    
    	[DataMember]
    	public string UpdateName
    	{ 
    		get { return _updateName; }
    		set
    		{
    			if (_updateName != value )
    			{
    				_updateName = value;
    				OnPropertyChanged(() => UpdateName);
    			}
    		}
    	}
    	
    	private Nullable<System.DateTime> _updateDate;
    
    	[DataMember]
    	public Nullable<System.DateTime> UpdateDate
    	{ 
    		get { return _updateDate; }
    		set
    		{
    			if (_updateDate != value )
    			{
    				_updateDate = value;
    				OnPropertyChanged(() => UpdateDate);
    			}
    		}
    	}
    	
    	private Nullable<short> _concurrencyValue;
    
    	[DataMember]
    	public Nullable<short> ConcurrencyValue
    	{ 
    		get { return _concurrencyValue; }
    		set
    		{
    			if (_concurrencyValue != value )
    			{
    				_concurrencyValue = value;
    				OnPropertyChanged(() => ConcurrencyValue);
    			}
    		}
    	}
    
    	
    	private gcsUser _gcsUser;
    
    	[DataMember]
    	public virtual gcsUser gcsUser
    	{ 
    		get { return _gcsUser; }
    		set
    		{
    			if (_gcsUser != value )
    			{
    				_gcsUser = value;
    				OnPropertyChanged(() => gcsUser);
    			}
    		}
    	}
    	
    	private InputOutputGroup _inputOutputGroup;
    
    	[DataMember]
    	public virtual InputOutputGroup InputOutputGroup
    	{ 
    		get { return _inputOutputGroup; }
    		set
    		{
    			if (_inputOutputGroup != value )
    			{
    				_inputOutputGroup = value;
    				OnPropertyChanged(() => InputOutputGroup);
    			}
    		}
    	}
    	
    	private InputOutputGroupCommand _inputOutputGroupCommand;
    
    	[DataMember]
    	public virtual InputOutputGroupCommand InputOutputGroupCommand
    	{ 
    		get { return _inputOutputGroupCommand; }
    		set
    		{
    			if (_inputOutputGroupCommand != value )
    			{
    				_inputOutputGroupCommand = value;
    				OnPropertyChanged(() => InputOutputGroupCommand);
    			}
    		}
    	}
    }
    
}
