//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Client.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
	using GCS.Core.Common.Core;
	using GCS.Core.Common.Contracts;	using FluentValidation;
    
	[DataContract]
	public partial class AccessPortalLoadToCpu : DbObjectBase
    {
        	
    	private System.Guid _accessPortalLoadToCpuUid;
    
    	[DataMember]
    	public System.Guid AccessPortalLoadToCpuUid
    	{ 
    		get { return _accessPortalLoadToCpuUid; }
    		set
    		{
    			if (_accessPortalLoadToCpuUid != value )
    			{
    				_accessPortalLoadToCpuUid = value;
    				OnPropertyChanged(() => AccessPortalLoadToCpuUid);
    			}
    		}
    	}
    	
    	private System.Guid _accessPortalGalaxyHardwareAddressUid;
    
    	[DataMember]
    	public System.Guid AccessPortalGalaxyHardwareAddressUid
    	{ 
    		get { return _accessPortalGalaxyHardwareAddressUid; }
    		set
    		{
    			if (_accessPortalGalaxyHardwareAddressUid != value )
    			{
    				_accessPortalGalaxyHardwareAddressUid = value;
    				OnPropertyChanged(() => AccessPortalGalaxyHardwareAddressUid);
    			}
    		}
    	}
    	
    	private System.Guid _cpuUid;
    
    	[DataMember]
    	public System.Guid CpuUid
    	{ 
    		get { return _cpuUid; }
    		set
    		{
    			if (_cpuUid != value )
    			{
    				_cpuUid = value;
    				OnPropertyChanged(() => CpuUid);
    			}
    		}
    	}
    	
    	private Nullable<System.DateTimeOffset> _lastForceLoadDate;
    
    	[DataMember]
    	public Nullable<System.DateTimeOffset> LastForceLoadDate
    	{ 
    		get { return _lastForceLoadDate; }
    		set
    		{
    			if (_lastForceLoadDate != value )
    			{
    				_lastForceLoadDate = value;
    				OnPropertyChanged(() => LastForceLoadDate);
    			}
    		}
    	}
    	
    	private Nullable<System.DateTimeOffset> _lastLoadedDate;
    
    	[DataMember]
    	public Nullable<System.DateTimeOffset> LastLoadedDate
    	{ 
    		get { return _lastLoadedDate; }
    		set
    		{
    			if (_lastLoadedDate != value )
    			{
    				_lastLoadedDate = value;
    				OnPropertyChanged(() => LastLoadedDate);
    			}
    		}
    	}
    
    	
    	private GalaxyCpu _galaxyCpu;
    
    	[DataMember]
    	public virtual GalaxyCpu GalaxyCpu
    	{ 
    		get { return _galaxyCpu; }
    		set
    		{
    			if (_galaxyCpu != value )
    			{
    				_galaxyCpu = value;
    				OnPropertyChanged(() => GalaxyCpu);
    			}
    		}
    	}
    }
    
}
