//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Client.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
	using GCS.Core.Common.Core;
	using FluentValidation;

    ////////////////////////////////////////////////////////////////////////////////////////////////////
    /// <summary>   Map of assa dsr time schedules. </summary>
    ///
    /// <remarks>   Kevin, 12/26/2018. </remarks>
    ////////////////////////////////////////////////////////////////////////////////////////////////////

	[DataContract]
	public partial class AssaDsrTimeScheduleMap : DbObjectBase
    {
    
    /*	// Move to partial class
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
	using GCS.Core.Common.Core;
	using FluentValidation;
    using System.Collections.ObjectModel;
    using GCS.Core.Common.Extensions;
    
    namespace GalaxySMS.Client.Entities
    {
        public partial class AssaDsrTimeScheduleMap
        {
        	public AssaDsrTimeScheduleMap()
        	{
        		Initialize();
        	}
        
        	public AssaDsrTimeScheduleMap(AssaDsrTimeScheduleMap e)
        	{
        		Initialize(e);
        	}
        
        	public void Initialize()
        	{
        }
        
        	public void Initialize(AssaDsrTimeScheduleMap e)
        	{
        		Initialize();
        		if( e == null )
        			return;
        		this.AssaDsrTimeScheduleMapUid = e.AssaDsrTimeScheduleMapUid;
        		this.TimeScheduleUid = e.TimeScheduleUid;
        		this.AssaDsrUid = e.AssaDsrUid;
        		this.AssaDsrScheduleId = e.AssaDsrScheduleId;
        		this.InsertName = e.InsertName;
        		this.InsertDate = e.InsertDate;
        		this.UpdateName = e.UpdateName;
        		this.UpdateDate = e.UpdateDate;
        		this.ConcurrencyValue = e.ConcurrencyValue;
        		
        	}
        
        	public AssaDsrTimeScheduleMap Clone(AssaDsrTimeScheduleMap e)
        	{
        		return new AssaDsrTimeScheduleMap(e);
        	}
        
        	public bool Equals(AssaDsrTimeScheduleMap other)
        	{
        		return base.Equals(other);
        	}
        	
        	public bool IsPrimaryKeyEqual(AssaDsrTimeScheduleMap other)
        	{
        		if( other == null ) 
        			return false;
        
        		if(other.AssaDsrTimeScheduleMapUid != this.AssaDsrTimeScheduleMapUid )
        			return false;
        		return true;
        	}
        
        	public override int GetHashCode()
        	{
        		return base.GetHashCode();
        	}
        
        	public override string ToString()
        	{
        		return base.ToString();
        	}
        }
    }
    */
    
    	
        /// <summary>   The assa dsr time schedule map UID. </summary>
    	private System.Guid _assaDsrTimeScheduleMapUid;

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the assa dsr time schedule map UID. </summary>
        ///
        /// <value> The assa dsr time schedule map UID. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

    	[DataMember]
    	public System.Guid AssaDsrTimeScheduleMapUid
    	{ 
    		get { return _assaDsrTimeScheduleMapUid; }
    		set
    		{
    			if (_assaDsrTimeScheduleMapUid != value )
    			{
    				_assaDsrTimeScheduleMapUid = value;
    				OnPropertyChanged(() => AssaDsrTimeScheduleMapUid);
    			}
    		}
    	}
    	
        /// <summary>   The time schedule UID. </summary>
    	private System.Guid _timeScheduleUid;

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the time schedule UID. </summary>
        ///
        /// <value> The time schedule UID. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

    	[DataMember]
    	public System.Guid TimeScheduleUid
    	{ 
    		get { return _timeScheduleUid; }
    		set
    		{
    			if (_timeScheduleUid != value )
    			{
    				_timeScheduleUid = value;
    				OnPropertyChanged(() => TimeScheduleUid);
    			}
    		}
    	}
    	
        /// <summary>   The assa dsr UID. </summary>
    	private System.Guid _assaDsrUid;

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the assa dsr UID. </summary>
        ///
        /// <value> The assa dsr UID. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

    	[DataMember]
    	public System.Guid AssaDsrUid
    	{ 
    		get { return _assaDsrUid; }
    		set
    		{
    			if (_assaDsrUid != value )
    			{
    				_assaDsrUid = value;
    				OnPropertyChanged(() => AssaDsrUid);
    			}
    		}
    	}
    	
        /// <summary>   Identifier for the assa dsr schedule. </summary>
    	private string _assaDsrScheduleId;

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the identifier of the assa dsr schedule. </summary>
        ///
        /// <value> The identifier of the assa dsr schedule. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

    	[DataMember]
    	public string AssaDsrScheduleId
    	{ 
    		get { return _assaDsrScheduleId; }
    		set
    		{
    			if (_assaDsrScheduleId != value )
    			{
    				_assaDsrScheduleId = value;
    				OnPropertyChanged(() => AssaDsrScheduleId);
    			}
    		}
    	}
    	
        /// <summary>   Name of the insert. </summary>
    	private string _insertName;

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the name of the insert. </summary>
        ///
        /// <value> The name of the insert. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

    	[DataMember]
    	public string InsertName
    	{ 
    		get { return _insertName; }
    		set
    		{
    			if (_insertName != value )
    			{
    				_insertName = value;
    				OnPropertyChanged(() => InsertName);
    			}
    		}
    	}
    	
        /// <summary>   The insert date. </summary>
    	private System.DateTimeOffset _insertDate;

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the insert date. </summary>
        ///
        /// <value> The insert date. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

    	[DataMember]
    	public System.DateTimeOffset InsertDate
    	{ 
    		get { return _insertDate; }
    		set
    		{
    			if (_insertDate != value )
    			{
    				_insertDate = value;
    				OnPropertyChanged(() => InsertDate);
    			}
    		}
    	}
    	
        /// <summary>   Name of the update. </summary>
    	private string _updateName;

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the name of the update. </summary>
        ///
        /// <value> The name of the update. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

    	[DataMember]
    	public string UpdateName
    	{ 
    		get { return _updateName; }
    		set
    		{
    			if (_updateName != value )
    			{
    				_updateName = value;
    				OnPropertyChanged(() => UpdateName);
    			}
    		}
    	}
    	
        /// <summary>   The update. </summary>
    	private Nullable<System.DateTimeOffset> _updateDate;

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the update. </summary>
        ///
        /// <value> The update date. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

    	[DataMember]
    	public Nullable<System.DateTimeOffset> UpdateDate
    	{ 
    		get { return _updateDate; }
    		set
    		{
    			if (_updateDate != value )
    			{
    				_updateDate = value;
    				OnPropertyChanged(() => UpdateDate);
    			}
    		}
    	}
    	
        /// <summary>   The concurrency value. </summary>
    	private Nullable<short> _concurrencyValue;

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the concurrency value. </summary>
        ///
        /// <value> The concurrency value. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

    	[DataMember]
    	public Nullable<short> ConcurrencyValue
    	{ 
    		get { return _concurrencyValue; }
    		set
    		{
    			if (_concurrencyValue != value )
    			{
    				_concurrencyValue = value;
    				OnPropertyChanged(() => ConcurrencyValue);
    			}
    		}
    	}
    
    	
        /// <summary>   The assa dsr. </summary>
    	private AssaDsr _assaDsr;

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the assa dsr. </summary>
        ///
        /// <value> The assa dsr. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

    	[DataMember]
    	public virtual AssaDsr AssaDsr
    	{ 
    		get { return _assaDsr; }
    		set
    		{
    			if (_assaDsr != value )
    			{
    				_assaDsr = value;
    				OnPropertyChanged(() => AssaDsr);
    			}
    		}
    	}
    }
    
}
