//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Client.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
	using GCS.Core.Common.Core;
	using GCS.Core.Common.Contracts;	using FluentValidation;
    
	[DataContract]
	public partial class gcsUserGroup : DbObjectBase, ITableEntityBase
    {
    	private System.Guid _userGroupId;
    
    	[DataMember]
    	public System.Guid UserGroupId
    	{ 
    		get { return _userGroupId; }
    		set
    		{
    			if (_userGroupId != value )
    			{
    				_userGroupId = value;
    				OnPropertyChanged(() => UserGroupId);
    			}
    		}
    	}
    	
    	private string _name;
    
    	[DataMember]
    	public string Name
    	{ 
    		get { return _name; }
    		set
    		{
    			if (_name != value )
    			{
    				_name = value;
    				OnPropertyChanged(() => Name);
    			}
    		}
    	}
    	
    	private string _description;
    
    	[DataMember]
    	public string Description
    	{ 
    		get { return _description; }
    		set
    		{
    			if (_description != value )
    			{
    				_description = value;
    				OnPropertyChanged(() => Description);
    			}
    		}
    	}
    	
    	private string _insertName;
    
    	[DataMember]
    	public string InsertName
    	{ 
    		get { return _insertName; }
    		set
    		{
    			if (_insertName != value )
    			{
    				_insertName = value;
    				OnPropertyChanged(() => InsertName);
    			}
    		}
    	}
    	
    	private System.DateTimeOffset _insertDate;
    
    	[DataMember]
    	public System.DateTimeOffset InsertDate
    	{ 
    		get { return _insertDate; }
    		set
    		{
    			if (_insertDate != value )
    			{
    				_insertDate = value;
    				OnPropertyChanged(() => InsertDate);
    			}
    		}
    	}
    	
    	private string _updateName;
    
    	[DataMember]
    	public string UpdateName
    	{ 
    		get { return _updateName; }
    		set
    		{
    			if (_updateName != value )
    			{
    				_updateName = value;
    				OnPropertyChanged(() => UpdateName);
    			}
    		}
    	}
    	
    	private Nullable<System.DateTimeOffset> _updateDate;
    
    	[DataMember]
    	public Nullable<System.DateTimeOffset> UpdateDate
    	{ 
    		get { return _updateDate; }
    		set
    		{
    			if (_updateDate != value )
    			{
    				_updateDate = value;
    				OnPropertyChanged(() => UpdateDate);
    			}
    		}
    	}
    	
    	private Nullable<short> _concurrencyValue;
    
    	[DataMember]
    	public Nullable<short> ConcurrencyValue
    	{ 
    		get { return _concurrencyValue; }
    		set
    		{
    			if (_concurrencyValue != value )
    			{
    				_concurrencyValue = value;
    				OnPropertyChanged(() => ConcurrencyValue);
    			}
    		}
    	}
    
    	
    	private ICollection<gcsUserGroupEntity> _gcsUserGroupEntities;
    
    	[DataMember]
    	public virtual ICollection<gcsUserGroupEntity> gcsUserGroupEntities
    	{ 
    		get { return _gcsUserGroupEntities; }
    		set
    		{
    			if (_gcsUserGroupEntities != value )
    			{
    				_gcsUserGroupEntities = value;
    				OnPropertyChanged(() => gcsUserGroupEntities);
    			}
    		}
    	}
    	
    	private ICollection<gcsUserUserGroup> _gcsUserUserGroups;
    
    	[DataMember]
    	public virtual ICollection<gcsUserUserGroup> gcsUserUserGroups
    	{ 
    		get { return _gcsUserUserGroups; }
    		set
    		{
    			if (_gcsUserUserGroups != value )
    			{
    				_gcsUserUserGroups = value;
    				OnPropertyChanged(() => gcsUserUserGroups);
    			}
    		}
    	}
    }
    
}
