//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Client.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
	using GCS.Core.Common.Core;
	using GCS.Core.Common.Contracts;	using FluentValidation;
    
	[DataContract]
	public partial class gcsUserGroupEntityRole : DbObjectBase, ITableEntityBase
    {
    	private System.Guid _userGroupEntityRoleId;
    
    	[DataMember]
    	public System.Guid UserGroupEntityRoleId
    	{ 
    		get { return _userGroupEntityRoleId; }
    		set
    		{
    			if (_userGroupEntityRoleId != value )
    			{
    				_userGroupEntityRoleId = value;
    				OnPropertyChanged(() => UserGroupEntityRoleId);
    			}
    		}
    	}
    	
    	private System.Guid _userGroupEntityId;
    
    	[DataMember]
    	public System.Guid UserGroupEntityId
    	{ 
    		get { return _userGroupEntityId; }
    		set
    		{
    			if (_userGroupEntityId != value )
    			{
    				_userGroupEntityId = value;
    				OnPropertyChanged(() => UserGroupEntityId);
    			}
    		}
    	}
    	
    	private System.Guid _roleId;
    
    	[DataMember]
    	public System.Guid RoleId
    	{ 
    		get { return _roleId; }
    		set
    		{
    			if (_roleId != value )
    			{
    				_roleId = value;
    				OnPropertyChanged(() => RoleId);
    			}
    		}
    	}
    	
    	private string _insertName;
    
    	[DataMember]
    	public string InsertName
    	{ 
    		get { return _insertName; }
    		set
    		{
    			if (_insertName != value )
    			{
    				_insertName = value;
    				OnPropertyChanged(() => InsertName);
    			}
    		}
    	}
    	
    	private System.DateTimeOffset _insertDate;
    
    	[DataMember]
    	public System.DateTimeOffset InsertDate
    	{ 
    		get { return _insertDate; }
    		set
    		{
    			if (_insertDate != value )
    			{
    				_insertDate = value;
    				OnPropertyChanged(() => InsertDate);
    			}
    		}
    	}
    	
    	private string _updateName;
    
    	[DataMember]
    	public string UpdateName
    	{ 
    		get { return _updateName; }
    		set
    		{
    			if (_updateName != value )
    			{
    				_updateName = value;
    				OnPropertyChanged(() => UpdateName);
    			}
    		}
    	}
    	
    	private Nullable<System.DateTimeOffset> _updateDate;
    
    	[DataMember]
    	public Nullable<System.DateTimeOffset> UpdateDate
    	{ 
    		get { return _updateDate; }
    		set
    		{
    			if (_updateDate != value )
    			{
    				_updateDate = value;
    				OnPropertyChanged(() => UpdateDate);
    			}
    		}
    	}
    	
    	private Nullable<short> _concurrencyValue;
    
    	[DataMember]
    	public Nullable<short> ConcurrencyValue
    	{ 
    		get { return _concurrencyValue; }
    		set
    		{
    			if (_concurrencyValue != value )
    			{
    				_concurrencyValue = value;
    				OnPropertyChanged(() => ConcurrencyValue);
    			}
    		}
    	}
    
    	
    	private gcsRole _gcsRole;
    
    	[DataMember]
    	public virtual gcsRole gcsRole
    	{ 
    		get { return _gcsRole; }
    		set
    		{
    			if (_gcsRole != value )
    			{
    				_gcsRole = value;
    				OnPropertyChanged(() => gcsRole);
    			}
    		}
    	}
    }
    
}
