//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using GCS.Core.Common.Contracts;
using GCS.Core.Common.Core;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using Swashbuckle.AspNetCore.Annotations;

namespace GalaxySMS.Api.Models.RequestModels
{
    public partial class GalaxyCpuPostReq
    {
        [Required]
        public System.Guid CpuUid { get; set; }

        [Required]
        public System.Guid GalaxyPanelUid { get; set; }

        [Required]
        [Range(1, 2)]
        public short CpuNumber { get; set; }

        public bool PreventFlashLoading { get; set; }

        public bool PreventDataLoading { get; set; }

        public bool DefaultEventLoggingOn { get; set; }

        public bool IsActive { get; set; }
        // Read only via API
        [StringLength(30)]
        [SwaggerSchema(ReadOnly = true)]
        public string SerialNumber { get; internal set; }

        [SwaggerSchema(ReadOnly = true)]
        public string FlashVersion { get; internal set; }

        [SwaggerSchema(ReadOnly = true)]
        public string IpAddress { get; internal set; }

        [SwaggerSchema(ReadOnly = true)]
        public int Model { get; internal set; }
    }
}
