//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using GCS.Core.Common.Contracts;
	using GCS.Core.Common.Core;
    public partial class AccessGroupLoadToCpu : EntityBase, IIdentifiableEntity, IEquatable<AccessGroupLoadToCpu>, ITableEntityBase
    {
    	public System.Guid AccessGroupLoadToCpuUid { get; set; }
    	public System.Guid AccessGroupUid { get; set; }
    	public System.Guid CpuUid { get; set; }
    	public Nullable<System.DateTimeOffset> LastLoadedDate { get; set; }
    	public Nullable<System.DateTimeOffset> LastForceLoadDate { get; set; }
    
    	public GalaxyCpu GalaxyCpu { get; set; }
    
    }
}
