//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using GCS.Core.Common.Contracts;
	using GCS.Core.Common.Core;
    public partial class AccessPortalAlarmEventAcknowledgment : EntityBase, IIdentifiableEntity, IEquatable<AccessPortalAlarmEventAcknowledgment>, ITableEntityBase
    {
    	public System.Guid AccessPortalAlarmEventAcknowledgmentUid { get; set; }
    	public System.Guid AccessPortalActivityEventUid { get; set; }
    	public System.Guid UserId { get; set; }
    	public string Response { get; set; }
    	public string InsertName { get; set; }
    	public System.DateTimeOffset InsertDate { get; set; }
    	public string UpdateName { get; set; }
    	public Nullable<System.DateTimeOffset> UpdateDate { get; set; }
    	public Nullable<short> ConcurrencyValue { get; set; }
    
    	//public AccessPortalActivityAlarmEvent AccessPortalActivityAlarmEvent { get; set; }
    
    }
}
