//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using GCS.Core.Common.Contracts;
	using GCS.Core.Common.Core;
    public partial class DateType : EntityBase, IIdentifiableEntity, IEquatable<DateType>
    {
    /*	// Move to partial class
    using System;
    using System.Collections.Generic;
    using GCS.Core.Common.Contracts;
	using GCS.Core.Common.Core;
    using GCS.Core.Common.Extensions;
    
    namespace GalaxySMS.Business.Entities
    {
        public partial class DateType
        {
        	public DateType()
        	{
        		Initialize();
        	}
        
        	public DateType(DateType e)
        	{
        		Initialize(e);
        	}
        
        	public void Initialize()
        	{
        	}
        
        	public void Initialize(DateType e)
        	{
        		Initialize();
        		if( e == null )
        			return;
        		this.DateTypeUid = e.DateTypeUid;
        		this.EntityId = e.EntityId;
        		this.DayTypeUid = e.DayTypeUid;
        		this.Date = e.Date;
        		this.InsertName = e.InsertName;
        		this.InsertDate = e.InsertDate;
        		this.UpdateName = e.UpdateName;
        		this.UpdateDate = e.UpdateDate;
        		this.ConcurrencyValue = e.ConcurrencyValue;
        		
        	}
        
        	public DateType Clone(DateType e)
        	{
        		return new DateType(e);
        	}
        
        	public bool Equals(DateType other)
        	{
        		return base.Equals(other);
        	}
        	
        	public bool IsPrimaryKeyEqual(DateType other)
        	{
        		if( other == null ) 
        			return false;
        
        		if(other.DateTypeUid != this.DateTypeUid )
        			return false;
        		return true;
        	}
        
        	public override int GetHashCode()
        	{
        		return base.GetHashCode();
        	}
        
        	public override string ToString()
        	{
        		return base.ToString();
        	}
        }
    }
    */
    	public System.Guid DateTypeUid { get; set; }
    	public System.Guid EntityId { get; set; }
    	public System.Guid DayTypeUid { get; set; }
    	public System.DateTimeOffset Date { get; set; }
        public string Title { get; set; }
        public string InsertName { get; set; }
    	public System.DateTimeOffset InsertDate { get; set; }
    	public string UpdateName { get; set; }
    	public Nullable<System.DateTimeOffset> UpdateDate { get; set; }
    	public Nullable<short> ConcurrencyValue { get; set; }
    
    	//public DayType DayType { get; set; }
    
    }
}
