//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using GCS.Core.Common.Contracts;
	using GCS.Core.Common.Core;
    public partial class GalaxyPanelModelInterfaceBoardSectionMode : EntityBase, IIdentifiableEntity, IEquatable<GalaxyPanelModelInterfaceBoardSectionMode>, ITableEntityBase
    {
    /*	// Move to partial class
    using System;
    using System.Collections.Generic;
    using GCS.Core.Common.Contracts;
	using GCS.Core.Common.Core;
    using GCS.Core.Common.Extensions;
    
    namespace GalaxySMS.Business.Entities
    {
        public partial class GalaxyPanelModelInterfaceBoardSectionMode
        {
        	public GalaxyPanelModelInterfaceBoardSectionMode()
        	{
        		Initialize();
        	}
        
        	public GalaxyPanelModelInterfaceBoardSectionMode(GalaxyPanelModelInterfaceBoardSectionMode e)
        	{
        		Initialize(e);
        	}
        
        	public void Initialize()
        	{
        	}
        
        	public void Initialize(GalaxyPanelModelInterfaceBoardSectionMode e)
        	{
        		Initialize();
        		if( e == null )
        			return;
        		this.GalaxyPanelModelInterfaceBoardSectionModeUid = e.GalaxyPanelModelInterfaceBoardSectionModeUid;
        		this.GalaxyPanelModelUid = e.GalaxyPanelModelUid;
        		this.InterfaceBoardSectionModeUid = e.InterfaceBoardSectionModeUid;
        		this.InsertName = e.InsertName;
        		this.InsertDate = e.InsertDate;
        		this.UpdateName = e.UpdateName;
        		this.UpdateDate = e.UpdateDate;
        		this.ConcurrencyValue = e.ConcurrencyValue;
        		
        	}
        
        	public GalaxyPanelModelInterfaceBoardSectionMode Clone(GalaxyPanelModelInterfaceBoardSectionMode e)
        	{
        		return new GalaxyPanelModelInterfaceBoardSectionMode(e);
        	}
        
        	public bool Equals(GalaxyPanelModelInterfaceBoardSectionMode other)
        	{
        		return base.Equals(other);
        	}
        	
        	public bool IsPrimaryKeyEqual(GalaxyPanelModelInterfaceBoardSectionMode other)
        	{
        		if( other == null ) 
        			return false;
        
        		if(other.GalaxyPanelModelInterfaceBoardSectionModeUid != this.GalaxyPanelModelInterfaceBoardSectionModeUid )
        			return false;
        		return true;
        	}
        
        	public override int GetHashCode()
        	{
        		return base.GetHashCode();
        	}
        
        	public override string ToString()
        	{
        		return base.ToString();
        	}
        }
    }
    */
    	public System.Guid GalaxyPanelModelInterfaceBoardSectionModeUid { get; set; }
    	public System.Guid GalaxyPanelModelUid { get; set; }
    	public System.Guid InterfaceBoardSectionModeUid { get; set; }
    	public string InsertName { get; set; }
    	public System.DateTimeOffset InsertDate { get; set; }
    	public string UpdateName { get; set; }
    	public Nullable<System.DateTimeOffset> UpdateDate { get; set; }
    	public Nullable<short> ConcurrencyValue { get; set; }
    
    	public GalaxyPanelModel GalaxyPanelModel { get; set; }
    	public InterfaceBoardSectionMode InterfaceBoardSectionMode { get; set; }
    
    }
}
