//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using GCS.Core.Common.Contracts;
	using GCS.Core.Common.Core;
    public partial class GalaxyCpu : EntityBase, IIdentifiableEntity, IEquatable<GalaxyCpu>, ITableEntityBase
    {

        public System.Guid CpuUid { get; set; }
    	public System.Guid GalaxyPanelUid { get; set; }
    	public int ClusterNumber { get; set; }
    	public int PanelNumber { get; set; }
    	public short CpuNumber { get; set; }
    	public string SerialNumber { get; set; }
    	public string IpAddress { get; set; }
    	public Nullable<int> Model { get; set; }
    	public bool PreventFlashLoading { get; set; }
    	public bool PreventDataLoading { get; set; }
        public bool DefaultEventLoggingOn { get; set; }
        public bool IsActive { get; set; }
        public string InsertName { get; set; }
    	public System.DateTimeOffset InsertDate { get; set; }
    	public string UpdateName { get; set; }
    	public Nullable<System.DateTimeOffset> UpdateDate { get; set; }
    	public Nullable<short> ConcurrencyValue { get; set; }
    	public System.Guid GalaxyCpuModelUid { get; set; }
    
    	public GalaxyCpuModel GalaxyCpuModel { get; set; }
        public int LastLogIndex { get; set; }
    }
}
