//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using GCS.Core.Common.Contracts;
	using GCS.Core.Common.Core;
    public partial class InputOutputGroupCommandAudit : EntityBase, IIdentifiableEntity, IEquatable<InputOutputGroupCommandAudit>, ITableEntityBase
    {
    /*	// Move to partial class
    using System;
    using System.Collections.Generic;
    using GCS.Core.Common.Contracts;
	using GCS.Core.Common.Core;
    using GCS.Core.Common.Extensions;
    
    namespace GalaxySMS.Business.Entities
    {
        public partial class InputOutputGroupCommandAudit
        {
        	public InputOutputGroupCommandAudit()
        	{
        		Initialize();
        	}
        
        	public InputOutputGroupCommandAudit(InputOutputGroupCommandAudit e)
        	{
        		Initialize(e);
        	}
        
        	public void Initialize()
        	{
        	}
        
        	public void Initialize(InputOutputGroupCommandAudit e)
        	{
        		Initialize();
        		if( e == null )
        			return;
        
        		this.IsDirty = e.IsDirty;
        		this.InputOutputGroupCommandAuditUid = e.InputOutputGroupCommandAuditUid;
        		this.UserId = e.UserId;
        		this.InputOutputGroupCommandUid = e.InputOutputGroupCommandUid;
        		this.InputOutputGroupUid = e.InputOutputGroupUid;
        		this.InsertName = e.InsertName;
        		this.InsertDate = e.InsertDate;
        		this.UpdateName = e.UpdateName;
        		this.UpdateDate = e.UpdateDate;
        		this.ConcurrencyValue = e.ConcurrencyValue;
        		
        	}
        
        	public bool IsAnythingDirty
        	{
        		get
        		{
        			//foreach( var o in InterfaceBoardSections)
        			//{
        			//	if (o.IsAnythingDirty == true)
        			//		return true;
        			//}
        			return IsDirty;                
        		}
        	}
        
        	public InputOutputGroupCommandAudit Clone(InputOutputGroupCommandAudit e)
        	{
        		return new InputOutputGroupCommandAudit(e);
        	}
        
        	public bool Equals(InputOutputGroupCommandAudit other)
        	{
        		return base.Equals(other);
        	}
        	
        	public bool IsPrimaryKeyEqual(InputOutputGroupCommandAudit other)
        	{
        		if( other == null ) 
        			return false;
        
        		if(other.InputOutputGroupCommandAuditUid != this.InputOutputGroupCommandAuditUid )
        			return false;
        		return true;
        	}
        
        	public override int GetHashCode()
        	{
        		return base.GetHashCode();
        	}
        
        	public override string ToString()
        	{
        		return base.ToString();
        	}
        }
    }
    */
    	public System.Guid InputOutputGroupCommandAuditUid { get; set; }
    	public System.Guid UserId { get; set; }
    	public System.Guid InputOutputGroupCommandUid { get; set; }
    	public System.Guid InputOutputGroupUid { get; set; }
    	public string InsertName { get; set; }
    	public System.DateTimeOffset InsertDate { get; set; }
    	public string UpdateName { get; set; }
    	public Nullable<System.DateTimeOffset> UpdateDate { get; set; }
    	public Nullable<short> ConcurrencyValue { get; set; }
    
    	public gcsUser gcsUser { get; set; }
    	public InputOutputGroup InputOutputGroup { get; set; }
    	public InputOutputGroupCommand InputOutputGroupCommand { get; set; }
    
    }
}
