//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySMS.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using GCS.Core.Common.Contracts;
	using GCS.Core.Common.Core;
    public partial class PersonPersonalAccessGroup : EntityBase, IIdentifiableEntity, IEquatable<PersonPersonalAccessGroup>, ITableEntityBase
    {
    	public System.Guid PersonClusterPermissionUid { get; set; }
    	public System.Guid TimeScheduleUid { get; set; }
    	public System.Guid ClusterUid { get; set; }
    	public int PersonalAccessGroupNumber { get; set; }
    	public string InsertName { get; set; }
    	public System.DateTimeOffset InsertDate { get; set; }
    	public string UpdateName { get; set; }
    	public Nullable<System.DateTimeOffset> UpdateDate { get; set; }
    	public Nullable<short> ConcurrencyValue { get; set; }
    
    	public PersonClusterPermission PersonClusterPermission { get; set; }
        public ICollection<Guid> AccessPortalUids { get; set; }
        public ICollection<Guid> DynamicAccessGroupUids { get; set; }

    }
}
